/*
 * Don't delete this file, it's autogenerated by the ACL icons build script
 */
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

import { IconBase } from '../../icon-base';

/** @deprecated Use `@sbb-esta/angular-icons` instead. */
@Component({
  selector: 'sbb-icon-service-yt',
  // tslint:disable-next-line
  template: `<svg [attr.class]="'sbb-svg-icon ' + svgClass" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 23 13"><path d="M3.1 7.6L0 0h2.8l1.9 5.5L8.9 0h3L5.7 7.6 4.5 13H1.9M12.4 0L12 2h3.7l-2.4 11H16l2.4-11H22l.4-2"/></svg>`,
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconServiceYtComponent extends IconBase {
  constructor() {
    super({ width: '23px', height: '13px', ratio: 1.7692307692307692 });
  }
}

/** @deprecated Use `@sbb-esta/angular-icons` instead. */
@NgModule({
  declarations: [IconServiceYtComponent],
  exports: [IconServiceYtComponent]
})
export class IconServiceYtModule {}
