/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

@Component({
  selector: 'svg[sbbIconLotusMedium]',
  template: `
    <svg:path
      fill="none"
      stroke="#000"
      d="M12.75 14.625c0 3.909 1.935 7.602 5.25 10.014 5.956-4.335 7-12.333 2.331-17.863A13.217 13.217 0 0018 4.61c-3.315 2.41-5.25 6.105-5.25 10.014zm-8.404 4.838a12.965 12.965 0 00-2.365 1.674A12.712 12.712 0 0015 27.74m6 0a12.71 12.71 0 0013.019-6.603 12.914 12.914 0 00-2.364-1.674m-21.16-8.654a12.673 12.673 0 00-4.966-.855c-1.443 6.8 2.853 13.497 9.638 15.017m10.337-14.162a12.673 12.673 0 014.967-.855c1.443 6.8-2.853 13.497-9.638 15.017"
    />
  `,
  styles: [
    `
      :host-context(.sbb-icon-fixed-size) {
        width: 36px;
        height: 36px;
      }
      :host-context(.sbb-icon-inherit-color) [fill]:not([fill='none']) {
        fill: currentColor;
      }
      :host-context(.sbb-icon-inherit-color) [stroke]:not([stroke='none']) {
        stroke: currentColor;
      }
    `
  ],
  host: {
    xmlns: 'http://www.w3.org/2000/svg',
    viewBox: '0 0 36 36',
    class: 'sbb-icon sbb-icon-kom sbb-icon-station',
    focusable: 'false'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SvgIconLotusMedium {}

@Component({
  selector: 'sbb-icon-lotus-medium',
  template: `
    <svg sbbIconLotusMedium></svg>
  `,
  host: {
    class: 'sbb-icon-wrapper'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconLotusMedium {}

@NgModule({
  declarations: [SvgIconLotusMedium, IconLotusMedium],
  exports: [SvgIconLotusMedium, IconLotusMedium]
})
export class IconLotusMediumModule {}
