/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

@Component({
  selector: 'svg[sbbIconShoppingBagSmall]',
  template: `
    <svg:path
      fill="none"
      stroke="#000"
      d="M5.5 7.457l-1 14h15l-1-14h-13zM14.493 11l.007-6a2.5 2.5 0 10-5 0v6"
    />
  `,
  styles: [
    `
      :host-context(.sbb-icon-fixed-size) {
        width: 24px;
        height: 24px;
      }
      :host-context(.sbb-icon-inherit-color) [fill]:not([fill='none']) {
        fill: currentColor;
      }
      :host-context(.sbb-icon-inherit-color) [stroke]:not([stroke='none']) {
        stroke: currentColor;
      }
    `
  ],
  host: {
    xmlns: 'http://www.w3.org/2000/svg',
    viewBox: '0 0 24 24',
    class: 'sbb-icon sbb-icon-kom sbb-icon-station',
    focusable: 'false'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SvgIconShoppingBagSmall {}

@Component({
  selector: 'sbb-icon-shopping-bag-small',
  template: `
    <svg sbbIconShoppingBagSmall></svg>
  `,
  host: {
    class: 'sbb-icon-wrapper'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconShoppingBagSmall {}

@NgModule({
  declarations: [SvgIconShoppingBagSmall, IconShoppingBagSmall],
  exports: [SvgIconShoppingBagSmall, IconShoppingBagSmall]
})
export class IconShoppingBagSmallModule {}
