/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

@Component({
  selector: 'svg[sbbIconToiletSmall]',
  template: `
    <svg:path
      fill="none"
      stroke="#000"
      d="M6.5 5.5a1 1 0 11-2.001 0 1 1 0 012 0zm1 8v-5h-4v5h1v6h2v-6h1zm11 2v4h-2v-4m2-10a1 1 0 11-2 0 1 1 0 012 0zm2 10l-2-7h-2l-2 7h6zM11.5 4v16"
    />
  `,
  styles: [
    `
      :host-context(.sbb-icon-fixed-size) {
        width: 24px;
        height: 24px;
      }
      :host-context(.sbb-icon-inherit-color) [fill]:not([fill='none']) {
        fill: currentColor;
      }
      :host-context(.sbb-icon-inherit-color) [stroke]:not([stroke='none']) {
        stroke: currentColor;
      }
    `
  ],
  host: {
    xmlns: 'http://www.w3.org/2000/svg',
    viewBox: '0 0 24 24',
    class: 'sbb-icon sbb-icon-kom sbb-icon-station',
    focusable: 'false'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SvgIconToiletSmall {}

@Component({
  selector: 'sbb-icon-toilet-small',
  template: `
    <svg sbbIconToiletSmall></svg>
  `,
  host: {
    class: 'sbb-icon-wrapper'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconToiletSmall {}

@NgModule({
  declarations: [SvgIconToiletSmall, IconToiletSmall],
  exports: [SvgIconToiletSmall, IconToiletSmall]
})
export class IconToiletSmallModule {}
