/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

@Component({
  selector: 'svg[sbbIconPercentSmall]',
  template: `
    <svg:path
      fill="none"
      stroke="#000"
      d="M11.498 9.997a1.5 1.5 0 11-3 0 1.5 1.5 0 013 0zM15.5 16a1.5 1.5 0 11-3 0 1.5 1.5 0 013 0zm-8 1.5l9-9-9 9z"
    />
  `,
  styles: [
    `
      :host-context(.sbb-icon-fixed-size) {
        width: 24px;
        height: 24px;
      }
      :host-context(.sbb-icon-inherit-color) [fill]:not([fill='none']) {
        fill: currentColor;
      }
      :host-context(.sbb-icon-inherit-color) [stroke]:not([stroke='none']) {
        stroke: currentColor;
      }
    `
  ],
  host: {
    xmlns: 'http://www.w3.org/2000/svg',
    viewBox: '0 0 24 24',
    class: 'sbb-icon sbb-icon-kom sbb-icon-timetable',
    focusable: 'false'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SvgIconPercentSmall {}

@Component({
  selector: 'sbb-icon-percent-small',
  template: `
    <svg sbbIconPercentSmall></svg>
  `,
  host: {
    class: 'sbb-icon-wrapper'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconPercentSmall {}

@NgModule({
  declarations: [SvgIconPercentSmall, IconPercentSmall],
  exports: [SvgIconPercentSmall, IconPercentSmall]
})
export class IconPercentSmallModule {}
