/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

@Component({
  selector: 'svg[sbbIconPunctualitySmall]',
  template: `
    <svg:g fill="none" fill-rule="evenodd" stroke="#000">
      <svg:path
        d="M3.5 13.5c0-.168.005-.334.015-.5M11 5.515c.166-.01.332-.015.5-.015m0 0a8 8 0 11-8 8m8-8V3m-1.5.5h3m-5 10l2.5 3 5.5-6"
      />
      <svg:path stroke-dasharray="1 1" d="M3.648 11.958a8.005 8.005 0 016.831-6.393" />
    </svg:g>
  `,
  styles: [
    `
      :host-context(.sbb-icon-fixed-size) {
        width: 24px;
        height: 24px;
      }
      :host-context(.sbb-icon-inherit-color) [fill]:not([fill='none']) {
        fill: currentColor;
      }
      :host-context(.sbb-icon-inherit-color) [stroke]:not([stroke='none']) {
        stroke: currentColor;
      }
    `
  ],
  host: {
    xmlns: 'http://www.w3.org/2000/svg',
    viewBox: '0 0 24 24',
    class: 'sbb-icon sbb-icon-kom sbb-icon-timetable',
    focusable: 'false'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SvgIconPunctualitySmall {}

@Component({
  selector: 'sbb-icon-punctuality-small',
  template: `
    <svg sbbIconPunctualitySmall></svg>
  `,
  host: {
    class: 'sbb-icon-wrapper'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconPunctualitySmall {}

@NgModule({
  declarations: [SvgIconPunctualitySmall, IconPunctualitySmall],
  exports: [SvgIconPunctualitySmall, IconPunctualitySmall]
})
export class IconPunctualitySmallModule {}
