/*
 * Don't delete this file, it's autogenerated by the ACL icons build script
 */
import { NgModule } from '@angular/core';

import { IconUtilizationHighModule } from './icon-utilization-high.module';
import { IconUtilizationLowModule } from './icon-utilization-low.module';
import { IconUtilizationMediumModule } from './icon-utilization-medium.module';

@NgModule({
  imports: [
    IconUtilizationHighModule,
    IconUtilizationLowModule,
    IconUtilizationMediumModule,
  ],
  exports: [
    IconUtilizationHighModule,
    IconUtilizationLowModule,
    IconUtilizationMediumModule,
  ]
})
export class IconCollectionWebshopUtilizationModule { }
