/*
 * Don't delete this file, it's autogenerated by the ACL icons build script
 */
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

import { IconBase } from '../../icon-base';

/** @deprecated Use `@sbb-esta/angular-icons` instead. */
@Component({
  selector: 'sbb-icon-trainformation-low-floor',
  // tslint:disable-next-line
  template: `<svg [attr.class]="'sbb-svg-icon ' + svgClass" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M12 5l-2.1 9.9L7.1 5H3.8L1 18h2.5L5.6 8l2.7 10h3.4l2.8-13m1.8 0l-2.7 13h2.6l1.2-5.7h4.3l.4-2h-4.3l.7-3.3H23l.5-2"/></svg>`,
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconTrainformationLowFloorComponent extends IconBase {
  constructor() {
    super({ width: '24px', height: '24px', ratio: 1 });
  }
}

/** @deprecated Use `@sbb-esta/angular-icons` instead. */
@NgModule({
  declarations: [IconTrainformationLowFloorComponent],
  exports: [IconTrainformationLowFloorComponent]
})
export class IconTrainformationLowFloorModule {}
