/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

@Component({
  selector: 'svg[sbbIconBrochureSmall]',
  template: `
    <svg:path
      fill="none"
      stroke="#000"
      d="M13 9l6-2m-6 5l6-2m-6 5l6-2m-6 5l6-2M4 7l6 2m-6 1l6 2m-6 1l6 2m-6 1l6 2m1.5-11.5l9-3v15l-9 3-9-3v-15l9 3zm0 15v-15"
    />
  `,
  styles: [
    `
      :host-context(.sbb-icon-fixed-size) {
        width: 24px;
        height: 24px;
      }
      :host-context(.sbb-icon-inherit-color) [fill]:not([fill='none']) {
        fill: currentColor;
      }
      :host-context(.sbb-icon-inherit-color) [stroke]:not([stroke='none']) {
        stroke: currentColor;
      }
    `
  ],
  host: {
    xmlns: 'http://www.w3.org/2000/svg',
    viewBox: '0 0 24 24',
    class: 'sbb-icon sbb-icon-kom sbb-icon-hardware',
    focusable: 'false'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SvgIconBrochureSmall {}

@Component({
  selector: 'sbb-icon-brochure-small',
  template: `
    <svg sbbIconBrochureSmall></svg>
  `,
  host: {
    class: 'sbb-icon-wrapper'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconBrochureSmall {}

@NgModule({
  declarations: [SvgIconBrochureSmall, IconBrochureSmall],
  exports: [SvgIconBrochureSmall, IconBrochureSmall]
})
export class IconBrochureSmallModule {}
