name: "Download intermediate bazel cache"
description: "Downloads and decompresses the bazel cache as an artefact"
inputs:
  key:
    description: 'Base name of the artefact'
    required: true
    default: 'bazel-cache'
runs:
  using: "composite"
  steps:
    - name: "Bazel: Download cache artifacts"
      uses: actions/download-artifact@v6
      with:
        name: ${{ inputs.key }}-artifact
        path: ~/.bazel-cache/
    - name: "Bazel: Unpack artifacts"
      run: |
        cd ~/.bazel-cache/
        tar -I zstd -xf ${{ inputs.key }}.tar.zst
        rm -f ${{ inputs.key }}.tar.zst
      shell: bash
