/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

@Component({
  selector: 'svg[sbbIconPowerPlugSmall]',
  template: `
    <svg:path
      fill="none"
      stroke="#000"
      d="M6.5 7.5h12V12c0 2.027-1.659 3.5-3.5 3.5h-5c-2.078 0-3.5-1.748-3.5-3.5V7.5zm2-4.5v4.5m8-4.5v4.5m-6 8v3h4v-3m-2 5.5v-2.5"
    />
  `,
  styles: [
    `
      :host-context(.sbb-icon-fixed-size) {
        width: 24px;
        height: 24px;
      }
      :host-context(.sbb-icon-inherit-color) [fill]:not([fill='none']) {
        fill: currentColor;
      }
      :host-context(.sbb-icon-inherit-color) [stroke]:not([stroke='none']) {
        stroke: currentColor;
      }
    `
  ],
  host: {
    xmlns: 'http://www.w3.org/2000/svg',
    viewBox: '0 0 24 24',
    class: 'sbb-icon sbb-icon-kom sbb-icon-hardware',
    focusable: 'false'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SvgIconPowerPlugSmall {}

@Component({
  selector: 'sbb-icon-power-plug-small',
  template: `
    <svg sbbIconPowerPlugSmall></svg>
  `,
  host: {
    class: 'sbb-icon-wrapper'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconPowerPlugSmall {}

@NgModule({
  declarations: [SvgIconPowerPlugSmall, IconPowerPlugSmall],
  exports: [SvgIconPowerPlugSmall, IconPowerPlugSmall]
})
export class IconPowerPlugSmallModule {}
