/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

@Component({
  selector: 'svg[sbbIconSpeakerMedium]',
  template: `
    <svg:path
      fill="none"
      stroke="#000"
      d="M20.25 9.1v17.797l-7.979-6.657H6.75v-4.498h5.521L20.25 9.1zm7.159 17.752l-3.4-2.102m3.4-15.601l-3.4 2.101m5.396 2.413L24.01 15m0 5.999l5.394 1.34M30 18h-5.99"
    />
  `,
  styles: [
    `
      :host-context(.sbb-icon-fixed-size) {
        width: 36px;
        height: 36px;
      }
      :host-context(.sbb-icon-inherit-color) [fill]:not([fill='none']) {
        fill: currentColor;
      }
      :host-context(.sbb-icon-inherit-color) [stroke]:not([stroke='none']) {
        stroke: currentColor;
      }
    `
  ],
  host: {
    xmlns: 'http://www.w3.org/2000/svg',
    viewBox: '0 0 36 36',
    class: 'sbb-icon sbb-icon-kom sbb-icon-hardware',
    focusable: 'false'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SvgIconSpeakerMedium {}

@Component({
  selector: 'sbb-icon-speaker-medium',
  template: `
    <svg sbbIconSpeakerMedium></svg>
  `,
  host: {
    class: 'sbb-icon-wrapper'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconSpeakerMedium {}

@NgModule({
  declarations: [SvgIconSpeakerMedium, IconSpeakerMedium],
  exports: [SvgIconSpeakerMedium, IconSpeakerMedium]
})
export class IconSpeakerMediumModule {}
