/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

@Component({
  selector: 'svg[sbbIconSaHn]',
  template: `
    <svg:g fill="#000" fill-rule="evenodd">
      <svg:path
        d="M4.541 1.037h2.801L6.161 6.678h5.642l1.179-5.64h2.801L12.862 15h-2.8l1.28-6.12H5.701L4.421 15H1.62zM18.94 1.037h3.54l2.981 10.603h.041l2.28-10.603h2.64L27.402 15H23.8L20.88 4.298h-.04L18.62 15h-2.68z"
      />
    </svg:g>
  `,
  styles: [
    `
      :host-context(.sbb-icon-fixed-size) {
        width: 32px;
        height: 16px;
      }
      :host-context(.sbb-icon-inherit-color) [fill]:not([fill='none']) {
        fill: currentColor;
      }
      :host-context(.sbb-icon-inherit-color) [stroke]:not([stroke='none']) {
        stroke: currentColor;
      }
    `
  ],
  host: {
    xmlns: 'http://www.w3.org/2000/svg',
    viewBox: '0 0 32 16',
    class: 'sbb-icon sbb-icon-fpl sbb-icon-timetable-attributes',
    focusable: 'false'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SvgIconSaHn {}

@Component({
  selector: 'sbb-icon-sa-hn',
  template: `
    <svg sbbIconSaHn></svg>
  `,
  host: {
    class: 'sbb-icon-wrapper'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconSaHn {}

@NgModule({
  declarations: [SvgIconSaHn, IconSaHn],
  exports: [SvgIconSaHn, IconSaHn]
})
export class IconSaHnModule {}
