/*
 * Autogenerated by schematics
 */
import { NgModule } from '@angular/core';

import { IconProductBexModule } from './icon-product-bex.module';
import { IconProductCnlModule } from './icon-product-cnl.module';
import { IconProductEcModule } from './icon-product-ec.module';
import { IconProductEnModule } from './icon-product-en.module';
import { IconProductGexModule } from './icon-product-gex.module';
import { IconProductIc1Module } from './icon-product-ic-1.module';
import { IconProductIc11Module } from './icon-product-ic-11.module';
import { IconProductIc2Module } from './icon-product-ic-2.module';
import { IconProductIc21Module } from './icon-product-ic-21.module';
import { IconProductIc3Module } from './icon-product-ic-3.module';
import { IconProductIc4Module } from './icon-product-ic-4.module';
import { IconProductIc5Module } from './icon-product-ic-5.module';
import { IconProductIc51Module } from './icon-product-ic-51.module';
import { IconProductIc6Module } from './icon-product-ic-6.module';
import { IconProductIc61Module } from './icon-product-ic-61.module';
import { IconProductIc7Module } from './icon-product-ic-7.module';
import { IconProductIc8Module } from './icon-product-ic-8.module';
import { IconProductIc9Module } from './icon-product-ic-9.module';
import { IconProductIcModule } from './icon-product-ic.module';
import { IconProductIceModule } from './icon-product-ice.module';
import { IconProductIcnModule } from './icon-product-icn.module';
import { IconProductIr13Module } from './icon-product-ir-13.module';
import { IconProductIr15Module } from './icon-product-ir-15.module';
import { IconProductIr16Module } from './icon-product-ir-16.module';
import { IconProductIr17Module } from './icon-product-ir-17.module';
import { IconProductIr25Module } from './icon-product-ir-25.module';
import { IconProductIr26Module } from './icon-product-ir-26.module';
import { IconProductIr27Module } from './icon-product-ir-27.module';
import { IconProductIr35Module } from './icon-product-ir-35.module';
import { IconProductIr36Module } from './icon-product-ir-36.module';
import { IconProductIr37Module } from './icon-product-ir-37.module';
import { IconProductIr45Module } from './icon-product-ir-45.module';
import { IconProductIr46Module } from './icon-product-ir-46.module';
import { IconProductIr55Module } from './icon-product-ir-55.module';
import { IconProductIr56Module } from './icon-product-ir-56.module';
import { IconProductIr65Module } from './icon-product-ir-65.module';
import { IconProductIr66Module } from './icon-product-ir-66.module';
import { IconProductIr70Module } from './icon-product-ir-70.module';
import { IconProductIr75Module } from './icon-product-ir-75.module';
import { IconProductIr90Module } from './icon-product-ir-90.module';
import { IconProductIr95Module } from './icon-product-ir-95.module';
import { IconProductIrModule } from './icon-product-ir.module';
import { IconProductNjModule } from './icon-product-nj.module';
import { IconProductPeModule } from './icon-product-pe.module';
import { IconProductReModule } from './icon-product-re.module';
import { IconProductRjModule } from './icon-product-rj.module';
import { IconProductRjxModule } from './icon-product-rjx.module';
import { IconProductRxModule } from './icon-product-rx.module';
import { IconProductSnModule } from './icon-product-sn.module';
import { IconProductTgvModule } from './icon-product-tgv.module';
import { IconProductVaeModule } from './icon-product-vae.module';

const modules = [
  IconProductBexModule,
  IconProductCnlModule,
  IconProductEcModule,
  IconProductEnModule,
  IconProductGexModule,
  IconProductIcModule,
  IconProductIceModule,
  IconProductIcnModule,
  IconProductIc1Module,
  IconProductIc11Module,
  IconProductIc2Module,
  IconProductIc21Module,
  IconProductIc3Module,
  IconProductIc4Module,
  IconProductIc5Module,
  IconProductIc51Module,
  IconProductIc6Module,
  IconProductIc61Module,
  IconProductIc7Module,
  IconProductIc8Module,
  IconProductIc9Module,
  IconProductIrModule,
  IconProductIr13Module,
  IconProductIr15Module,
  IconProductIr16Module,
  IconProductIr17Module,
  IconProductIr25Module,
  IconProductIr26Module,
  IconProductIr27Module,
  IconProductIr35Module,
  IconProductIr36Module,
  IconProductIr37Module,
  IconProductIr45Module,
  IconProductIr46Module,
  IconProductIr55Module,
  IconProductIr56Module,
  IconProductIr65Module,
  IconProductIr66Module,
  IconProductIr70Module,
  IconProductIr75Module,
  IconProductIr90Module,
  IconProductIr95Module,
  IconProductNjModule,
  IconProductPeModule,
  IconProductReModule,
  IconProductRjModule,
  IconProductRjxModule,
  IconProductRxModule,
  IconProductSnModule,
  IconProductTgvModule,
  IconProductVaeModule
];

@NgModule({
  imports: modules,
  exports: modules
})
export class IconCollectionTimetableProductsModule {}
