/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

@Component({
  selector: 'svg[sbbIconNewspaperMedium]',
  template: `
    <svg:path
      fill="none"
      stroke="#000"
      d="M27.75 25.5V6.75H5.25v19.503a2.998 2.998 0 002.998 2.997h19.505a2.998 2.998 0 002.997-2.997V11.25h-3m-19.5 6h6v-4.5h-6v4.5zm8.25-1.5h9m-9-3h9m-18-3h18m-9 10.5h9m-9 3h9m-18-3H15m-7.5 3H15m-7.5 3h18"
    />
  `,
  styles: [
    `
      :host-context(.sbb-icon-fixed-size) {
        width: 36px;
        height: 36px;
      }
      :host-context(.sbb-icon-inherit-color) [fill]:not([fill='none']) {
        fill: currentColor;
      }
      :host-context(.sbb-icon-inherit-color) [stroke]:not([stroke='none']) {
        stroke: currentColor;
      }
    `
  ],
  host: {
    xmlns: 'http://www.w3.org/2000/svg',
    viewBox: '0 0 36 36',
    class: 'sbb-icon sbb-icon-kom sbb-icon-basic',
    focusable: 'false'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SvgIconNewspaperMedium {}

@Component({
  selector: 'sbb-icon-newspaper-medium',
  template: `
    <svg sbbIconNewspaperMedium></svg>
  `,
  host: {
    class: 'sbb-icon-wrapper'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconNewspaperMedium {}

@NgModule({
  declarations: [SvgIconNewspaperMedium, IconNewspaperMedium],
  exports: [SvgIconNewspaperMedium, IconNewspaperMedium]
})
export class IconNewspaperMediumModule {}
