/*
 * Don't delete this file, it's autogenerated by the ACL icons build script
 */
import { NgModule } from '@angular/core';

import { IconCollectionBaseModule } from './base/icon-collection-base.module';
import { IconCollectionCampaignsModule } from './campaigns/icon-collection-campaigns.module';
import { IconCollectionLeisureHolidaysModule } from './leisure_holidays/icon-collection-leisure-holidays.module';
import { IconCollectionProductsModule } from './products/icon-collection-products.module';
import { IconCollectionWeatherModule } from './weather/icon-collection-weather.module';
import { IconCollectionWebshopModule } from './webshop/icon-collection-webshop.module';

/** @deprecated Use `@sbb-esta/angular-icons` instead. */
@NgModule({
  imports: [
    IconCollectionBaseModule,
    IconCollectionLeisureHolidaysModule,
    IconCollectionProductsModule,
    IconCollectionWeatherModule,
    IconCollectionCampaignsModule,
    IconCollectionWebshopModule
  ],
  exports: [
    IconCollectionBaseModule,
    IconCollectionLeisureHolidaysModule,
    IconCollectionProductsModule,
    IconCollectionWeatherModule,
    IconCollectionCampaignsModule,
    IconCollectionWebshopModule
  ]
})
export class IconCollectionModule {}
