
/*
* Don't delete this file, it's autogenerated by the ACL icons build script
*/
import { NgModule } from '@angular/core';
import { IconCollectionBaseModule } from '../../svg-icons/svg-icons';

/**
 * @deprecated Use IconCollectionBaseModule
 */
@NgModule({
  imports: [IconCollectionBaseModule],
  exports: [IconCollectionBaseModule],
})
export class IconBaseModule { }
