/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

@Component({
  selector: 'svg[sbbIconSaIi]',
  template: `
    <svg:g fill="#000" fill-rule="evenodd">
      <svg:path d="M4.28 1.038H7.2L4.26 15H1.34zM9.84 1.038h2.92L9.82 15H6.9z" />
    </svg:g>
  `,
  styles: [
    `
      :host-context(.sbb-icon-fixed-size) {
        width: 14px;
        height: 16px;
      }
      :host-context(.sbb-icon-inherit-color) [fill]:not([fill='none']) {
        fill: currentColor;
      }
      :host-context(.sbb-icon-inherit-color) [stroke]:not([stroke='none']) {
        stroke: currentColor;
      }
    `
  ],
  host: {
    xmlns: 'http://www.w3.org/2000/svg',
    viewBox: '0 0 14 16',
    class: 'sbb-icon sbb-icon-fpl sbb-icon-timetable-attributes',
    focusable: 'false'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SvgIconSaIi {}

@Component({
  selector: 'sbb-icon-sa-ii',
  template: `
    <svg sbbIconSaIi></svg>
  `,
  host: {
    class: 'sbb-icon-wrapper'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconSaIi {}

@NgModule({
  declarations: [SvgIconSaIi, IconSaIi],
  exports: [SvgIconSaIi, IconSaIi]
})
export class IconSaIiModule {}
