/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

@Component({
  selector: 'svg[sbbIconArrowsCircleMedium]',
  template: `
    <svg:path
      fill="none"
      stroke="#000"
      d="M6.765 18c.012-6.213 5.058-11.241 11.27-11.23 4.369.01 9.358 3.52 11.2 7.48m.015-6.735l-.015 6.735H22.5M29.25 18c-.024 6.22-5.087 11.245-11.308 11.221-4.341-.015-9.322-3.531-11.177-7.456M6.75 28.5l.015-6.735 6.735-.015"
    />
  `,
  styles: [
    `
      :host-context(.sbb-icon-fixed-size) {
        width: 36px;
        height: 36px;
      }
      :host-context(.sbb-icon-inherit-color) [fill]:not([fill='none']) {
        fill: currentColor;
      }
      :host-context(.sbb-icon-inherit-color) [stroke]:not([stroke='none']) {
        stroke: currentColor;
      }
    `
  ],
  host: {
    xmlns: 'http://www.w3.org/2000/svg',
    viewBox: '0 0 36 36',
    class: 'sbb-icon sbb-icon-kom sbb-icon-arrow',
    focusable: 'false'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SvgIconArrowsCircleMedium {}

@Component({
  selector: 'sbb-icon-arrows-circle-medium',
  template: `
    <svg sbbIconArrowsCircleMedium></svg>
  `,
  host: {
    class: 'sbb-icon-wrapper'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconArrowsCircleMedium {}

@NgModule({
  declarations: [SvgIconArrowsCircleMedium, IconArrowsCircleMedium],
  exports: [SvgIconArrowsCircleMedium, IconArrowsCircleMedium]
})
export class IconArrowsCircleMediumModule {}
