/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

@Component({
  selector: 'svg[sbbIconChevronSmallLeftSmall]',
  template: `
    <svg:path fill="none" stroke="#000" d="M13.675 8.096L9.725 12l3.948 3.904" />
  `,
  styles: [
    `
      :host-context(.sbb-icon-fixed-size) {
        width: 24px;
        height: 24px;
      }
      :host-context(.sbb-icon-inherit-color) [fill]:not([fill='none']) {
        fill: currentColor;
      }
      :host-context(.sbb-icon-inherit-color) [stroke]:not([stroke='none']) {
        stroke: currentColor;
      }
    `
  ],
  host: {
    xmlns: 'http://www.w3.org/2000/svg',
    viewBox: '0 0 24 24',
    class: 'sbb-icon sbb-icon-kom sbb-icon-arrow',
    focusable: 'false'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SvgIconChevronSmallLeftSmall {}

@Component({
  selector: 'sbb-icon-chevron-small-left-small',
  template: `
    <svg sbbIconChevronSmallLeftSmall></svg>
  `,
  host: {
    class: 'sbb-icon-wrapper'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconChevronSmallLeftSmall {}

@NgModule({
  declarations: [SvgIconChevronSmallLeftSmall, IconChevronSmallLeftSmall],
  exports: [SvgIconChevronSmallLeftSmall, IconChevronSmallLeftSmall]
})
export class IconChevronSmallLeftSmallModule {}
