/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

@Component({
  selector: 'svg[sbbIconDriverlessBusMedium]',
  template: `
    <svg:path
      fill="none"
      stroke="#000"
      d="M9.75 24.75v3h4.5v-3m-4.5-10.5h-1.5v1.5h1.5m16.5-1.5h1.5v1.5h-1.5m0 1.501l-16.5-.001m4.5 3.75a.751.751 0 00-1.5 0 .75.75 0 001.5 0zm9 0a.751.751 0 00-1.5 0 .75.75 0 001.5 0zm6 1.5v-3m3 4.5v-6m-25.5 1.5v3m-3-4.5v6m22.5.75H9.75V10.5a3.75 3.75 0 013.75-3.75h9a3.75 3.75 0 013.75 3.75v14.25zm-4.498 0v3h4.498v-3M22.5 9.75l-9-.001"
    />
  `,
  styles: [
    `
      :host-context(.sbb-icon-fixed-size) {
        width: 36px;
        height: 36px;
      }
      :host-context(.sbb-icon-inherit-color) [fill]:not([fill='none']) {
        fill: currentColor;
      }
      :host-context(.sbb-icon-inherit-color) [stroke]:not([stroke='none']) {
        stroke: currentColor;
      }
    `
  ],
  host: {
    xmlns: 'http://www.w3.org/2000/svg',
    viewBox: '0 0 36 36',
    class: 'sbb-icon sbb-icon-kom sbb-icon-transport',
    focusable: 'false'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SvgIconDriverlessBusMedium {}

@Component({
  selector: 'sbb-icon-driverless-bus-medium',
  template: `
    <svg sbbIconDriverlessBusMedium></svg>
  `,
  host: {
    class: 'sbb-icon-wrapper'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconDriverlessBusMedium {}

@NgModule({
  declarations: [SvgIconDriverlessBusMedium, IconDriverlessBusMedium],
  exports: [SvgIconDriverlessBusMedium, IconDriverlessBusMedium]
})
export class IconDriverlessBusMediumModule {}
