/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

@Component({
  selector: 'svg[sbbIconFaceSmilingSmall]',
  template: `
    <svg:path
      fill="none"
      stroke="#000"
      d="M20.5 12c0 4.746-3.754 8.5-8.5 8.5S3.5 16.746 3.5 12c0-4.747 3.754-8.5 8.5-8.5s8.5 3.753 8.5 8.5zM7.447 14.5c.762 1.77 2.482 3 4.553 3 2.072 0 3.79-1.23 4.553-3M9 8.5a.5.5 0 100 1 .5.5 0 000-1m6 0a.5.5 0 100 1 .5.5 0 000-1"
    />
  `,
  styles: [
    `
      :host-context(.sbb-icon-fixed-size) {
        width: 24px;
        height: 24px;
      }
      :host-context(.sbb-icon-inherit-color) [fill]:not([fill='none']) {
        fill: currentColor;
      }
      :host-context(.sbb-icon-inherit-color) [stroke]:not([stroke='none']) {
        stroke: currentColor;
      }
    `
  ],
  host: {
    xmlns: 'http://www.w3.org/2000/svg',
    viewBox: '0 0 24 24',
    class: 'sbb-icon sbb-icon-kom sbb-icon-community',
    focusable: 'false'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SvgIconFaceSmilingSmall {}

@Component({
  selector: 'sbb-icon-face-smiling-small',
  template: `
    <svg sbbIconFaceSmilingSmall></svg>
  `,
  host: {
    class: 'sbb-icon-wrapper'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconFaceSmilingSmall {}

@NgModule({
  declarations: [SvgIconFaceSmilingSmall, IconFaceSmilingSmall],
  exports: [SvgIconFaceSmilingSmall, IconFaceSmilingSmall]
})
export class IconFaceSmilingSmallModule {}
