/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

@Component({
  selector: 'svg[sbbIconUserGroupRoundTableSmall]',
  template: `
    <svg:path
      fill="none"
      stroke="#000"
      d="M20.5 16.5c0 1.657-4.029 3-9 3s-9-1.343-9-3 4.029-3 9-3 9 1.343 9 3zm-7-8.5c0 1.381-.896 2.5-2 2.5s-2-1.119-2-2.5.896-2.5 2-2.5 2 1.119 2 2.5zm0 0c0 1.381-.896 2.5-2 2.5s-2-1.119-2-2.5.896-2.5 2-2.5 2 1.119 2 2.5zm5 1c0 1.381-.896 2.5-2 2.5s-2-1.119-2-2.5.896-2.5 2-2.5 2 1.119 2 2.5zm-10 0c0 1.381-.896 2.5-2 2.5s-2-1.119-2-2.5.896-2.5 2-2.5 2 1.119 2 2.5zm5.963 4.67c-.13-1.663-.8-3.05-1.722-3.724m-2.482 0c-.922.675-1.592 2.061-1.722 3.724m1.722-3.724c-.922.675-1.592 2.061-1.722 3.724m.264-1.443c-.285-.543-.646-.985-1.056-1.286m-2.49.002c-1.007.734-1.716 2.32-1.748 4.18m15.987.003c-.03-1.862-.738-3.451-1.748-4.185m-2.492 0c-.412.299-.771.74-1.056 1.285"
    />
  `,
  styles: [
    `
      :host-context(.sbb-icon-fixed-size) {
        width: 24px;
        height: 24px;
      }
      :host-context(.sbb-icon-inherit-color) [fill]:not([fill='none']) {
        fill: currentColor;
      }
      :host-context(.sbb-icon-inherit-color) [stroke]:not([stroke='none']) {
        stroke: currentColor;
      }
    `
  ],
  host: {
    xmlns: 'http://www.w3.org/2000/svg',
    viewBox: '0 0 24 24',
    class: 'sbb-icon sbb-icon-kom sbb-icon-user',
    focusable: 'false'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SvgIconUserGroupRoundTableSmall {}

@Component({
  selector: 'sbb-icon-user-group-round-table-small',
  template: `
    <svg sbbIconUserGroupRoundTableSmall></svg>
  `,
  host: {
    class: 'sbb-icon-wrapper'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconUserGroupRoundTableSmall {}

@NgModule({
  declarations: [SvgIconUserGroupRoundTableSmall, IconUserGroupRoundTableSmall],
  exports: [SvgIconUserGroupRoundTableSmall, IconUserGroupRoundTableSmall]
})
export class IconUserGroupRoundTableSmallModule {}
