/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

@Component({
  selector: 'svg[sbbIconDocumentPptSmall]',
  template: `
    <svg:g fill="none" fill-rule="evenodd">
      <svg:path stroke="#000" d="M6.509 4.5h5.99l5 5v10h-11l.01-15zm5.991 0v5h5" />
      <svg:path
        fill="#000"
        d="M8.668 15.556v.85h.597c.176 0 .304-.033.382-.094.097-.076.145-.189.145-.338 0-.15-.056-.263-.167-.336-.081-.055-.213-.082-.396-.082h-.561zM8 15.002h1.235c.208 0 .371.013.491.037a.951.951 0 01.324.135c.266.175.4.44.4.792 0 .313-.111.56-.331.738a.876.876 0 01-.321.165c-.12.034-.268.05-.443.05h-.687V18H8v-2.998zm3.484.554v.85h.597c.176 0 .304-.033.382-.094.097-.076.145-.189.145-.338 0-.15-.056-.263-.167-.336-.081-.055-.213-.082-.396-.082h-.561zm-.668-.554h1.235c.208 0 .37.013.49.037a.951.951 0 01.325.135c.266.175.4.44.4.792 0 .313-.111.56-.331.738a.876.876 0 01-.321.165c-.12.034-.268.05-.443.05h-.687V18h-.668v-2.998zm5.184 0v.555h-.93V18h-.668v-2.444h-.925v-.554H16z"
      />
    </svg:g>
  `,
  styles: [
    `
      :host-context(.sbb-icon-fixed-size) {
        width: 24px;
        height: 24px;
      }
      :host-context(.sbb-icon-inherit-color) [fill]:not([fill='none']) {
        fill: currentColor;
      }
      :host-context(.sbb-icon-inherit-color) [stroke]:not([stroke='none']) {
        stroke: currentColor;
      }
    `
  ],
  host: {
    xmlns: 'http://www.w3.org/2000/svg',
    viewBox: '0 0 24 24',
    class: 'sbb-icon sbb-icon-kom sbb-icon-document',
    focusable: 'false'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SvgIconDocumentPptSmall {}

@Component({
  selector: 'sbb-icon-document-ppt-small',
  template: `
    <svg sbbIconDocumentPptSmall></svg>
  `,
  host: {
    class: 'sbb-icon-wrapper'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconDocumentPptSmall {}

@NgModule({
  declarations: [SvgIconDocumentPptSmall, IconDocumentPptSmall],
  exports: [SvgIconDocumentPptSmall, IconDocumentPptSmall]
})
export class IconDocumentPptSmallModule {}
