/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

@Component({
  selector: 'svg[sbbIconDocumentStandardSmall]',
  template: `
    <svg:path fill="none" stroke="#000" d="M6.5 4.5h6l5 5v10h-11v-15zm11 5h-5v-5" />
  `,
  styles: [
    `
      :host-context(.sbb-icon-fixed-size) {
        width: 24px;
        height: 24px;
      }
      :host-context(.sbb-icon-inherit-color) [fill]:not([fill='none']) {
        fill: currentColor;
      }
      :host-context(.sbb-icon-inherit-color) [stroke]:not([stroke='none']) {
        stroke: currentColor;
      }
    `
  ],
  host: {
    xmlns: 'http://www.w3.org/2000/svg',
    viewBox: '0 0 24 24',
    class: 'sbb-icon sbb-icon-kom sbb-icon-document',
    focusable: 'false'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SvgIconDocumentStandardSmall {}

@Component({
  selector: 'sbb-icon-document-standard-small',
  template: `
    <svg sbbIconDocumentStandardSmall></svg>
  `,
  host: {
    class: 'sbb-icon-wrapper'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconDocumentStandardSmall {}

@NgModule({
  declarations: [SvgIconDocumentStandardSmall, IconDocumentStandardSmall],
  exports: [SvgIconDocumentStandardSmall, IconDocumentStandardSmall]
})
export class IconDocumentStandardSmallModule {}
