/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

@Component({
  selector: 'svg[sbbIconDocumentImageMedium]',
  template: `
    <svg:path
      fill="none"
      stroke="#000"
      d="M9.75 6.75h9l7.5 7.5v15H9.75V6.75zm9 0v7.5h7.5m-3 10.492l-1.5-6.007-3 4.51-3-8.995-3 10.492h10.5z"
    />
  `,
  styles: [
    `
      :host-context(.sbb-icon-fixed-size) {
        width: 36px;
        height: 36px;
      }
      :host-context(.sbb-icon-inherit-color) [fill]:not([fill='none']) {
        fill: currentColor;
      }
      :host-context(.sbb-icon-inherit-color) [stroke]:not([stroke='none']) {
        stroke: currentColor;
      }
    `
  ],
  host: {
    xmlns: 'http://www.w3.org/2000/svg',
    viewBox: '0 0 36 36',
    class: 'sbb-icon sbb-icon-kom sbb-icon-document',
    focusable: 'false'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SvgIconDocumentImageMedium {}

@Component({
  selector: 'sbb-icon-document-image-medium',
  template: `
    <svg sbbIconDocumentImageMedium></svg>
  `,
  host: {
    class: 'sbb-icon-wrapper'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconDocumentImageMedium {}

@NgModule({
  declarations: [SvgIconDocumentImageMedium, IconDocumentImageMedium],
  exports: [SvgIconDocumentImageMedium, IconDocumentImageMedium]
})
export class IconDocumentImageMediumModule {}
