/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

@Component({
  selector: 'svg[sbbIconFolderPlusSmall]',
  template: `
    <svg:path fill="none" stroke="#000" d="M19.5 15v5M17 17.5h5m-7 0H4.5v-9h10l1-2h3.995L19.5 13" />
  `,
  styles: [
    `
      :host-context(.sbb-icon-fixed-size) {
        width: 24px;
        height: 24px;
      }
      :host-context(.sbb-icon-inherit-color) [fill]:not([fill='none']) {
        fill: currentColor;
      }
      :host-context(.sbb-icon-inherit-color) [stroke]:not([stroke='none']) {
        stroke: currentColor;
      }
    `
  ],
  host: {
    xmlns: 'http://www.w3.org/2000/svg',
    viewBox: '0 0 24 24',
    class: 'sbb-icon sbb-icon-kom sbb-icon-document',
    focusable: 'false'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SvgIconFolderPlusSmall {}

@Component({
  selector: 'sbb-icon-folder-plus-small',
  template: `
    <svg sbbIconFolderPlusSmall></svg>
  `,
  host: {
    class: 'sbb-icon-wrapper'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconFolderPlusSmall {}

@NgModule({
  declarations: [SvgIconFolderPlusSmall, IconFolderPlusSmall],
  exports: [SvgIconFolderPlusSmall, IconFolderPlusSmall]
})
export class IconFolderPlusSmallModule {}
