/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

@Component({
  selector: 'svg[sbbIconFolderOpenArrowMedium]',
  template: `
    <svg:path
      fill="none"
      stroke="#000"
      d="M26.25 18.75v-3h-12v-3H5.236l.014 18h21.225l3.975-12H9.525l-4.275 12M15.75 7.5l4.5 4.5 4.5-4.5M20.25 3v9"
    />
  `,
  styles: [
    `
      :host-context(.sbb-icon-fixed-size) {
        width: 36px;
        height: 36px;
      }
      :host-context(.sbb-icon-inherit-color) [fill]:not([fill='none']) {
        fill: currentColor;
      }
      :host-context(.sbb-icon-inherit-color) [stroke]:not([stroke='none']) {
        stroke: currentColor;
      }
    `
  ],
  host: {
    xmlns: 'http://www.w3.org/2000/svg',
    viewBox: '0 0 36 36',
    class: 'sbb-icon sbb-icon-kom sbb-icon-document',
    focusable: 'false'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SvgIconFolderOpenArrowMedium {}

@Component({
  selector: 'sbb-icon-folder-open-arrow-medium',
  template: `
    <svg sbbIconFolderOpenArrowMedium></svg>
  `,
  host: {
    class: 'sbb-icon-wrapper'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconFolderOpenArrowMedium {}

@NgModule({
  declarations: [SvgIconFolderOpenArrowMedium, IconFolderOpenArrowMedium],
  exports: [SvgIconFolderOpenArrowMedium, IconFolderOpenArrowMedium]
})
export class IconFolderOpenArrowMediumModule {}
