/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

@Component({
  selector: 'svg[sbbIconFolderOpenMedium]',
  template: `
    <svg:path
      fill="none"
      stroke="#000"
      d="M27.765 14.25v-3h-12v-3H6.75l.015 18h21.223l3.977-12H11.04l-4.275 12"
    />
  `,
  styles: [
    `
      :host-context(.sbb-icon-fixed-size) {
        width: 36px;
        height: 36px;
      }
      :host-context(.sbb-icon-inherit-color) [fill]:not([fill='none']) {
        fill: currentColor;
      }
      :host-context(.sbb-icon-inherit-color) [stroke]:not([stroke='none']) {
        stroke: currentColor;
      }
    `
  ],
  host: {
    xmlns: 'http://www.w3.org/2000/svg',
    viewBox: '0 0 36 36',
    class: 'sbb-icon sbb-icon-kom sbb-icon-document',
    focusable: 'false'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SvgIconFolderOpenMedium {}

@Component({
  selector: 'sbb-icon-folder-open-medium',
  template: `
    <svg sbbIconFolderOpenMedium></svg>
  `,
  host: {
    class: 'sbb-icon-wrapper'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconFolderOpenMedium {}

@NgModule({
  declarations: [SvgIconFolderOpenMedium, IconFolderOpenMedium],
  exports: [SvgIconFolderOpenMedium, IconFolderOpenMedium]
})
export class IconFolderOpenMediumModule {}
