/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

@Component({
  selector: 'svg[sbbIconCloudRainSnowMedium]',
  template: `
    <svg:path
      fill="none"
      stroke="#000"
      d="M10.8 15.3c-.348-2.913 2.819-4.473 4.8-2.85 2.25-5.1 9.6-2.55 7.95 3 3.75-.15 3.804 6.3-1.05 6.3H12c-5.05 0-4.411-6.45-1.2-6.45zm15.45 10.2a.75.75 0 11-1.5 0 .75.75 0 011.5 0zm-6 0a.75.75 0 11-1.5 0 .75.75 0 011.5 0zm3 4.5a.75.75 0 11-1.5 0 .75.75 0 011.5 0zm-13.5-6l-1.5 3 1.5-3zm6 0l-1.5 3 1.5-3zm-3 0l-3 6 3-6z"
    />
  `,
  styles: [
    `
      :host-context(.sbb-icon-fixed-size) {
        width: 36px;
        height: 36px;
      }
      :host-context(.sbb-icon-inherit-color) [fill]:not([fill='none']) {
        fill: currentColor;
      }
      :host-context(.sbb-icon-inherit-color) [stroke]:not([stroke='none']) {
        stroke: currentColor;
      }
    `
  ],
  host: {
    xmlns: 'http://www.w3.org/2000/svg',
    viewBox: '0 0 36 36',
    class: 'sbb-icon sbb-icon-kom sbb-icon-weather',
    focusable: 'false'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SvgIconCloudRainSnowMedium {}

@Component({
  selector: 'sbb-icon-cloud-rain-snow-medium',
  template: `
    <svg sbbIconCloudRainSnowMedium></svg>
  `,
  host: {
    class: 'sbb-icon-wrapper'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconCloudRainSnowMedium {}

@NgModule({
  declarations: [SvgIconCloudRainSnowMedium, IconCloudRainSnowMedium],
  exports: [SvgIconCloudRainSnowMedium, IconCloudRainSnowMedium]
})
export class IconCloudRainSnowMediumModule {}
