/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

@Component({
  selector: 'svg[sbbIconSunshineSmall]',
  template: `
    <svg:path
      fill="none"
      stroke="#000"
      d="M16.5 12.5a3.98 3.98 0 01-3.977 3.994 3.995 3.995 0 01-3.995-3.995c0-2.207 1.765-3.999 3.972-3.999 2.206 0 4 1.793 4 4zM4 12.5h3.003H4zm2.393-6.184L8.67 8.593 6.393 6.316zm6.119-2.328v3.015-3.015zm6.145 2.42l-2.264 2.238 2.264-2.238zM21 12.5h-3.006H21zm-2.33 6.093l-2.266-2.257 2.267 2.257zm-6.17-.6v3.003-3.003zm-3.843-1.592l-2.262 2.261 2.262-2.26z"
    />
  `,
  styles: [
    `
      :host-context(.sbb-icon-fixed-size) {
        width: 24px;
        height: 24px;
      }
      :host-context(.sbb-icon-inherit-color) [fill]:not([fill='none']) {
        fill: currentColor;
      }
      :host-context(.sbb-icon-inherit-color) [stroke]:not([stroke='none']) {
        stroke: currentColor;
      }
    `
  ],
  host: {
    xmlns: 'http://www.w3.org/2000/svg',
    viewBox: '0 0 24 24',
    class: 'sbb-icon sbb-icon-kom sbb-icon-weather',
    focusable: 'false'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SvgIconSunshineSmall {}

@Component({
  selector: 'sbb-icon-sunshine-small',
  template: `
    <svg sbbIconSunshineSmall></svg>
  `,
  host: {
    class: 'sbb-icon-wrapper'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconSunshineSmall {}

@NgModule({
  declarations: [SvgIconSunshineSmall, IconSunshineSmall],
  exports: [SvgIconSunshineSmall, IconSunshineSmall]
})
export class IconSunshineSmallModule {}
