packages:
  - .
  - docs
  - src/angular
  - src/angular-experimental
  - src/components-examples
  - src/journey-maps
  - src/journey-maps-wc

catalog:
  '@angular-devkit/build-angular': 22.0.0-next.7
  '@angular-devkit/core': 22.0.0-next.7
  '@angular-devkit/schematics': 22.0.0-next.7
  '@angular/animations': 21.2.8
  '@angular/build': 22.0.0-next.7
  '@angular/cdk': 22.0.0-next.7
  '@angular/cli': 22.0.0-next.7
  '@angular/common': 22.0.0-next.12
  '@angular/compiler-cli': 22.0.0-next.12
  '@angular/compiler': 22.0.0-next.12
  '@angular/core': 22.0.0-next.12
  '@angular/elements': 22.0.0-next.12
  '@angular/ssr': 22.0.0-next.7
  '@angular/forms': 22.0.0-next.12
  '@angular/localize': 22.0.0-next.12
  '@angular/platform-browser': 22.0.0-next.12
  '@angular/platform-browser-dynamic': 22.0.0-next.12
  '@angular/platform-server': 22.0.0-next.12
  '@angular/router': 22.0.0-next.12
  '@schematics/angular': 22.0.0-next.7
  'rxjs': 7.8.1
