packages:
  - .
  - docs
  - src/angular
  - src/angular-experimental
  - src/components-examples
  - src/journey-maps
  - src/journey-maps-wc

catalog:
  '@angular-devkit/build-angular': 20.3.6
  '@angular-devkit/core': 20.3.6
  '@angular-devkit/schematics': 20.3.6
  '@angular/animations': 20.3.6
  '@angular/build': 20.3.6
  '@angular/cdk': 20.2.9
  '@angular/cli': 20.3.6
  '@angular/common': 20.3.6
  '@angular/compiler-cli': 20.3.6
  '@angular/compiler': 20.3.6
  '@angular/core': 20.3.6
  '@angular/elements': 20.3.6
  '@angular/ssr': 20.3.6
  '@angular/forms': 20.3.6
  '@angular/localize': 20.3.6
  '@angular/platform-browser': 20.3.6
  '@angular/platform-browser-dynamic': 20.3.6
  '@angular/platform-server': 20.3.6
  '@angular/router': 20.3.6
  '@schematics/angular': 20.3.6
  'rxjs': 7.8.1
