packages:
  - .
  - docs
  - src/angular
  - src/angular-experimental
  - src/components-examples
  - src/journey-maps
  - src/journey-maps-wc

catalog:
  '@angular-devkit/build-angular': 21.1.0
  '@angular-devkit/core': 21.1.0
  '@angular-devkit/schematics': 21.1.0
  '@angular/animations': 21.1.0
  '@angular/build': 21.1.0
  '@angular/cdk': 21.1.0
  '@angular/cli': 21.1.0
  '@angular/common': 21.1.0
  '@angular/compiler-cli': 21.1.0
  '@angular/compiler': 21.1.0
  '@angular/core': 21.1.0
  '@angular/elements': 21.1.0
  '@angular/ssr': 21.1.0
  '@angular/forms': 21.1.0
  '@angular/localize': 21.1.0
  '@angular/platform-browser': 21.1.0
  '@angular/platform-browser-dynamic': 21.1.0
  '@angular/platform-server': 21.1.0
  '@angular/router': 21.1.0
  '@schematics/angular': 21.1.0
  'rxjs': 7.8.1
