/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

@Component({
  selector: 'svg[sbbIconTimetableSmall]',
  template: `
    <svg:path
      fill="none"
      stroke="#000"
      d="M15.5 10.5c2.757 0 5 2.243 5 5 0 2.756-2.243 5-5 5s-5-2.244-5-5c0-2.757 2.243-5 5-5zM2 3.5h7-7zm9 0h4-4zm0 3h4-4zm6 0h5-5zm0-3h5-5zm-15 3h7-7zm0 3h7-7zm0 3h5-5zm0 3h5-5zm0 3h5-5zM15.5 12v3.5H19"
    />
  `,
  styles: [
    `
      :host-context(.sbb-icon-fixed-size) {
        width: 24px;
        height: 24px;
      }
      :host-context(.sbb-icon-inherit-color) [fill]:not([fill='none']) {
        fill: currentColor;
      }
      :host-context(.sbb-icon-inherit-color) [stroke]:not([stroke='none']) {
        stroke: currentColor;
      }
    `
  ],
  host: {
    xmlns: 'http://www.w3.org/2000/svg',
    viewBox: '0 0 24 24',
    class: 'sbb-icon sbb-icon-kom sbb-icon-timetable',
    focusable: 'false'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SvgIconTimetableSmall {}

@Component({
  selector: 'sbb-icon-timetable-small',
  template: `
    <svg sbbIconTimetableSmall></svg>
  `,
  host: {
    class: 'sbb-icon-wrapper'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconTimetableSmall {}

@NgModule({
  declarations: [SvgIconTimetableSmall, IconTimetableSmall],
  exports: [SvgIconTimetableSmall, IconTimetableSmall]
})
export class IconTimetableSmallModule {}
