/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

@Component({
  selector: 'svg[sbbIconWalkSlowMedium]',
  template: `
    <svg:g fill="none" fill-rule="evenodd">
      <svg:path
        stroke="#000"
        d="M23.25 30v-6.75l-1.5-2.86h-3v4.36L18 30m3.75-17.25v7.64h-3v-7.64m-2.947 7.553l-3.09 7.65-2.778-1.134 1.686-4.173 2.768 1.128M15.75 19.5v-3.75l3-3h3l1.5 3 2.25 3m-5.251-9c-.8 0-1.5-.7-1.5-1.5s.7-1.5 1.5-1.5 1.5.7 1.5 1.5-.7 1.5-1.5 1.5z"
      />
      <svg:path
        fill="#000"
        d="M9.36 27.463a.75.75 0 110 1.498.75.75 0 010-1.498zm2.782 1.123a.75.75 0 11-.002 1.499.75.75 0 01.002-1.499z"
      />
    </svg:g>
  `,
  styles: [
    `
      :host-context(.sbb-icon-fixed-size) {
        width: 36px;
        height: 36px;
      }
      :host-context(.sbb-icon-inherit-color) [fill]:not([fill='none']) {
        fill: currentColor;
      }
      :host-context(.sbb-icon-inherit-color) [stroke]:not([stroke='none']) {
        stroke: currentColor;
      }
    `
  ],
  host: {
    xmlns: 'http://www.w3.org/2000/svg',
    viewBox: '0 0 36 36',
    class: 'sbb-icon sbb-icon-kom sbb-icon-timetable',
    focusable: 'false'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SvgIconWalkSlowMedium {}

@Component({
  selector: 'sbb-icon-walk-slow-medium',
  template: `
    <svg sbbIconWalkSlowMedium></svg>
  `,
  host: {
    class: 'sbb-icon-wrapper'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconWalkSlowMedium {}

@NgModule({
  declarations: [SvgIconWalkSlowMedium, IconWalkSlowMedium],
  exports: [SvgIconWalkSlowMedium, IconWalkSlowMedium]
})
export class IconWalkSlowMediumModule {}
