/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

@Component({
  selector: 'svg[sbbIconWalkSmall]',
  template: `
    <svg:path
      fill="none"
      stroke="#000"
      d="M14.5 20v-4.5l-2-2h-2v3l-2 3m4-11v5h-2v-5m1-2c-.533 0-1-.466-1-1 0-.533.467-1 1-1 .533 0 1 .467 1 1 0 .534-.467 1-1 1zm-4 7.5v-3.5l3-2h2l2 2H17"
    />
  `,
  styles: [
    `
      :host-context(.sbb-icon-fixed-size) {
        width: 24px;
        height: 24px;
      }
      :host-context(.sbb-icon-inherit-color) [fill]:not([fill='none']) {
        fill: currentColor;
      }
      :host-context(.sbb-icon-inherit-color) [stroke]:not([stroke='none']) {
        stroke: currentColor;
      }
    `
  ],
  host: {
    xmlns: 'http://www.w3.org/2000/svg',
    viewBox: '0 0 24 24',
    class: 'sbb-icon sbb-icon-kom sbb-icon-timetable',
    focusable: 'false'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SvgIconWalkSmall {}

@Component({
  selector: 'sbb-icon-walk-small',
  template: `
    <svg sbbIconWalkSmall></svg>
  `,
  host: {
    class: 'sbb-icon-wrapper'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconWalkSmall {}

@NgModule({
  declarations: [SvgIconWalkSmall, IconWalkSmall],
  exports: [SvgIconWalkSmall, IconWalkSmall]
})
export class IconWalkSmallModule {}
