/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

@Component({
  selector: 'svg[sbbIconShoppingCartMedium]',
  template: `
    <svg:path
      fill="none"
      stroke="#000"
      d="M6 8.25h3.75v15H27m-17.25-12h19.5l-3 9.014-16.5-.014m5.987 7.5a1.5 1.5 0 11-3 0 1.5 1.5 0 013 0zm9.013 0c0 .829-.67 1.5-1.5 1.5s-1.5-.671-1.5-1.5a1.5 1.5 0 113 0z"
    />
  `,
  styles: [
    `
      :host-context(.sbb-icon-fixed-size) {
        width: 36px;
        height: 36px;
      }
      :host-context(.sbb-icon-inherit-color) [fill]:not([fill='none']) {
        fill: currentColor;
      }
      :host-context(.sbb-icon-inherit-color) [stroke]:not([stroke='none']) {
        stroke: currentColor;
      }
    `
  ],
  host: {
    xmlns: 'http://www.w3.org/2000/svg',
    viewBox: '0 0 36 36',
    class: 'sbb-icon sbb-icon-kom sbb-icon-basic',
    focusable: 'false'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SvgIconShoppingCartMedium {}

@Component({
  selector: 'sbb-icon-shopping-cart-medium',
  template: `
    <svg sbbIconShoppingCartMedium></svg>
  `,
  host: {
    class: 'sbb-icon-wrapper'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconShoppingCartMedium {}

@NgModule({
  declarations: [SvgIconShoppingCartMedium, IconShoppingCartMedium],
  exports: [SvgIconShoppingCartMedium, IconShoppingCartMedium]
})
export class IconShoppingCartMediumModule {}
