/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

@Component({
  selector: 'svg[sbbIconCrossMedium]',
  template: `
    <svg:path fill="none" stroke="#000" d="M18 18l-9 9 9-9 9 9-9-9zm0 0l9-9-9 9-9-9 9 9z" />
  `,
  styles: [
    `
      :host-context(.sbb-icon-fixed-size) {
        width: 36px;
        height: 36px;
      }
      :host-context(.sbb-icon-inherit-color) [fill]:not([fill='none']) {
        fill: currentColor;
      }
      :host-context(.sbb-icon-inherit-color) [stroke]:not([stroke='none']) {
        stroke: currentColor;
      }
    `
  ],
  host: {
    xmlns: 'http://www.w3.org/2000/svg',
    viewBox: '0 0 36 36',
    class: 'sbb-icon sbb-icon-kom sbb-icon-navigation',
    focusable: 'false'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SvgIconCrossMedium {}

@Component({
  selector: 'sbb-icon-cross-medium',
  template: `
    <svg sbbIconCrossMedium></svg>
  `,
  host: {
    class: 'sbb-icon-wrapper'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconCrossMedium {}

@NgModule({
  declarations: [SvgIconCrossMedium, IconCrossMedium],
  exports: [SvgIconCrossMedium, IconCrossMedium]
})
export class IconCrossMediumModule {}
