/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

@Component({
  selector: 'svg[sbbIconWheelchairUncertainMedium]',
  template: `
    <svg:path
      fill="none"
      stroke="#000"
      d="M9.75 12v8.25h7.5v8.25M7.047 16.4c-1.952.992-3.297 3.023-3.297 5.351 0 3.297 2.701 6 6 6 2.39 0 4.467-1.419 5.428-3.456m11.14 1.202v3M26.25 22.5c0-2.246.085-3.195 1.5-4.8L30 15.45c2.604-2.91 1.21-5.59-.712-6.617-3.095-1.509-7.538-.295-7.538 4.667M10.5 9A.75.75 0 119 9a.75.75 0 011.5 0z"
    />
  `,
  styles: [
    `
      :host-context(.sbb-icon-fixed-size) {
        width: 36px;
        height: 36px;
      }
      :host-context(.sbb-icon-inherit-color) [fill]:not([fill='none']) {
        fill: currentColor;
      }
      :host-context(.sbb-icon-inherit-color) [stroke]:not([stroke='none']) {
        stroke: currentColor;
      }
    `
  ],
  host: {
    xmlns: 'http://www.w3.org/2000/svg',
    viewBox: '0 0 36 36',
    class: 'sbb-icon sbb-icon-kom sbb-icon-timetable',
    focusable: 'false'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SvgIconWheelchairUncertainMedium {}

@Component({
  selector: 'sbb-icon-wheelchair-uncertain-medium',
  template: `
    <svg sbbIconWheelchairUncertainMedium></svg>
  `,
  host: {
    class: 'sbb-icon-wrapper'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconWheelchairUncertainMedium {}

@NgModule({
  declarations: [SvgIconWheelchairUncertainMedium, IconWheelchairUncertainMedium],
  exports: [SvgIconWheelchairUncertainMedium, IconWheelchairUncertainMedium]
})
export class IconWheelchairUncertainMediumModule {}
