/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

@Component({
  selector: 'svg[sbbIconCircleMinusMedium]',
  template: `
    <svg:path
      fill="none"
      stroke="#000"
      d="M18.75 5.25c6.627 0 12 5.373 12 12 0 6.628-5.373 12-12 12s-12-5.372-12-12c0-6.627 5.373-12 12-12zm-6.75 12h13.5"
    />
  `,
  styles: [
    `
      :host-context(.sbb-icon-fixed-size) {
        width: 36px;
        height: 36px;
      }
      :host-context(.sbb-icon-inherit-color) [fill]:not([fill='none']) {
        fill: currentColor;
      }
      :host-context(.sbb-icon-inherit-color) [stroke]:not([stroke='none']) {
        stroke: currentColor;
      }
    `
  ],
  host: {
    xmlns: 'http://www.w3.org/2000/svg',
    viewBox: '0 0 36 36',
    class: 'sbb-icon sbb-icon-kom sbb-icon-navigation',
    focusable: 'false'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SvgIconCircleMinusMedium {}

@Component({
  selector: 'sbb-icon-circle-minus-medium',
  template: `
    <svg sbbIconCircleMinusMedium></svg>
  `,
  host: {
    class: 'sbb-icon-wrapper'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconCircleMinusMedium {}

@NgModule({
  declarations: [SvgIconCircleMinusMedium, IconCircleMinusMedium],
  exports: [SvgIconCircleMinusMedium, IconCircleMinusMedium]
})
export class IconCircleMinusMediumModule {}
