/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

@Component({
  selector: 'svg[sbbIconHamburgerMenuSmall]',
  template: `
    <svg:path fill="none" stroke="#000" d="M20 5.5H4h16zm0 14H4h16zm0-7H4h16z" />
  `,
  styles: [
    `
      :host-context(.sbb-icon-fixed-size) {
        width: 24px;
        height: 24px;
      }
      :host-context(.sbb-icon-inherit-color) [fill]:not([fill='none']) {
        fill: currentColor;
      }
      :host-context(.sbb-icon-inherit-color) [stroke]:not([stroke='none']) {
        stroke: currentColor;
      }
    `
  ],
  host: {
    xmlns: 'http://www.w3.org/2000/svg',
    viewBox: '0 0 24 24',
    class: 'sbb-icon sbb-icon-kom sbb-icon-navigation',
    focusable: 'false'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SvgIconHamburgerMenuSmall {}

@Component({
  selector: 'sbb-icon-hamburger-menu-small',
  template: `
    <svg sbbIconHamburgerMenuSmall></svg>
  `,
  host: {
    class: 'sbb-icon-wrapper'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconHamburgerMenuSmall {}

@NgModule({
  declarations: [SvgIconHamburgerMenuSmall, IconHamburgerMenuSmall],
  exports: [SvgIconHamburgerMenuSmall, IconHamburgerMenuSmall]
})
export class IconHamburgerMenuSmallModule {}
