/*
 * Autogenerated by schematics
 */
import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

import { IconBase } from '../icon-base';

@Component({
  selector: 'sbb-icon-railway-switch',
  // tslint:disable:max-line-length
  template: `<svg [attr.class]="'sbb-svg-icon ' + svgClass" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 36 36"><path fill="none" stroke="#000" d="M8.25 27.75v-4.5h.003-.003v4.5H6h2.25zm0 0v2.852-2.852h.003-.003zm7.5-13.5v2.784-2.784h1.827-1.827v-4.5H18h-2.25V6v3.75H10.5h5.25v4.5H10.5h5.25zm-7.5 9H6h2.25V6v17.25zM6 9.75h2.25H6zm0 4.5h2.25H6zm4.5 4.492h4.12-4.12zM6 18.75h2.25H6zm14.528-9H19.5h1.03zM10.5 23.242h1.164H10.5zm4.5.008h7.5H15zm3-4.5h7.5H18zm3-4.5h7.5H21zm3-4.5h7.5H24zm-12 18h7.5H12zm3.75 0V30.6 27.75zm6.75-21L8.247 28.443M31.5 6.75L15.745 29.172"/></svg>`,
  // tslint:enable:max-line-length
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class IconRailwaySwitchComponent extends IconBase {
  constructor() {
    super({ width: '24px', height: '24px', ratio: 1 });
  }
}

@NgModule({
  imports: [CommonModule],
  declarations: [IconRailwaySwitchComponent],
  exports: [IconRailwaySwitchComponent],
})
export class IconRailwaySwitchModule { }
