/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

@Component({
  selector: 'svg[sbbIconProductIr16]',
  template: `
    <svg:g fill="none" fill-rule="evenodd">
      <svg:rect width="59" height="20" fill="#EB0000" rx="2" />
      <svg:path
        fill="#FFF"
        fill-rule="nonzero"
        d="M42.292 4.235V15.8H39.99V8.23h-2.712V6.553a5.796 5.796 0 001.376-.174c.353-.1.684-.266.974-.49.425-.327.712-.878.859-1.654h1.805zm11.155 2.888h-2.191c-.205-.892-.71-1.337-1.514-1.337-.851 0-1.456.524-1.813 1.574a9.318 9.318 0 00-.355 1.938 3.365 3.365 0 011.108-1.013c.44-.216.925-.322 1.415-.308a3.26 3.26 0 012.61 1.155 4.05 4.05 0 01.937 2.737c0 1.302-.42 2.349-1.26 3.14a3.84 3.84 0 01-2.729 1.068c-1.36 0-2.42-.516-3.177-1.547-.756-1.03-1.135-2.469-1.135-4.315 0-1.972.405-3.517 1.214-4.635a3.752 3.752 0 013.209-1.621c1.277 0 2.254.43 2.932 1.289a3.89 3.89 0 01.75 1.875zm-3.902 2.65a1.53 1.53 0 00-1.316.696c-.3.43-.455.946-.442 1.47a2.489 2.489 0 00.45 1.48c.294.453.801.72 1.34.704a1.586 1.586 0 001.332-.672c.318-.432.485-.958.473-1.495a2.44 2.44 0 00-.426-1.448 1.64 1.64 0 00-1.411-.736zM9.22 4.2h4.056L8.258 15.8H4.185zM25.98 12.366a.925.925 0 00.847-.553L30.119 4.2H15.984l-5.018 11.6h4.038l3.8-8.69h5.993l-1.201 2.775-5.226-.019 4.217 5.934h4.597l-3.124-3.434h1.92z"
      />
    </svg:g>
  `,
  styles: [
    `
      :host-context(.sbb-icon-fixed-size) {
        width: 59px;
        height: 20px;
      }
      :host-context(.sbb-icon-inherit-color) [fill]:not([fill='none']) {
        fill: currentColor;
      }
      :host-context(.sbb-icon-inherit-color) [stroke]:not([stroke='none']) {
        stroke: currentColor;
      }
    `
  ],
  host: {
    xmlns: 'http://www.w3.org/2000/svg',
    viewBox: '0 0 59 20',
    class: 'sbb-icon sbb-icon-fpl sbb-icon-timetable-products',
    focusable: 'false'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SvgIconProductIr16 {}

@Component({
  selector: 'sbb-icon-product-ir-16',
  template: `
    <svg sbbIconProductIr16></svg>
  `,
  host: {
    class: 'sbb-icon-wrapper'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconProductIr16 {}

@NgModule({
  declarations: [SvgIconProductIr16, IconProductIr16],
  exports: [SvgIconProductIr16, IconProductIr16]
})
export class IconProductIr16Module {}
