/*
 * Autogenerated by schematics
 */
import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

import { IconBase } from '../icon-base';

@Component({
  selector: 'sbb-icon-backpack',
  // tslint:disable:max-line-length
  template: `<svg [attr.class]="'sbb-svg-icon ' + svgClass" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 36 36"><path fill="none" stroke="#000" d="M8.25 13.5A6.75 6.75 0 0 1 15 6.75h6a6.75 6.75 0 0 1 6.75 6.75v18.75H8.25V13.5zm13.509-6.75l-.01-.75a2.25 2.25 0 0 0-2.25-2.25h-2.993A2.25 2.25 0 0 0 14.256 6l-.006.75M11.256 22.5a2.25 2.25 0 0 1 2.25-2.25H22.5a2.25 2.25 0 0 1 2.25 2.25m0 0v6.75h-13.5V22.5m2.25.75h9m-2.25 2.25v-2.25"/></svg>`,
  // tslint:enable:max-line-length
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class IconBackpackComponent extends IconBase {
  constructor() {
    super({ width: '24px', height: '24px', ratio: 1 });
  }
}

@NgModule({
  imports: [CommonModule],
  declarations: [IconBackpackComponent],
  exports: [IconBackpackComponent],
})
export class IconBackpackModule { }
