/*
 * Autogenerated by schematics
 */
import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

import { IconBase } from '../icon-base';

@Component({
  selector: 'sbb-icon-link',
  // tslint:disable:max-line-length
  template: `<svg [attr.class]="'sbb-svg-icon ' + svgClass" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 36 36"><path fill="none" stroke="#000" d="M19.901 16.41l-1.06-1.063a4.516 4.516 0 0 0-6.365 0l-6.363 6.365a4.513 4.513 0 0 0 0 6.364l1.06 1.06a4.514 4.514 0 0 0 6.364 0l3.72-3.72m-2.658-5.825l1.06 1.06a4.511 4.511 0 0 0 6.363 0l6.365-6.364a4.511 4.511 0 0 0 0-6.363l-1.06-1.06a4.513 4.513 0 0 0-6.365 0l-3.711 3.712"/></svg>`,
  // tslint:enable:max-line-length
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class IconLinkComponent extends IconBase {
  constructor() {
    super({ width: '24px', height: '24px', ratio: 1 });
  }
}

@NgModule({
  imports: [CommonModule],
  declarations: [IconLinkComponent],
  exports: [IconLinkComponent],
})
export class IconLinkModule { }
