/*
 * Don't delete this file, it's autogenerated by the ACL icons build script
 */
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

import { IconBase } from '../../icon-base';

@Component({
  selector: 'sbb-icon-him-construction',
  // tslint:disable-next-line:max-line-length
  template: `<svg [attr.class]="'sbb-svg-icon ' + svgClass" [attr.viewBox]="viewBox" [attr.preserveAspectRatio]="preserveAspectRatio" [attr.width]="width" [attr.height]="height" xmlns="http://www.w3.org/2000/svg"><path d="M10.7 6.5c.7 0 1.3-.6 1.3-1.4 0-.8-.6-1.4-1.3-1.4-.7 0-1.3.6-1.3 1.4 0 .8.6 1.4 1.3 1.4zm-.3 9.2c-.2.1-.5.4-.5.4l-.2.4-.2.3h-.4l-1 .8h10.1l-.5-.5-.4-.4h-.6l-.4-.4s-.3-.5-.3-.6.1-.5 0-.5c-.1-.1-.4-.3-.4-.3h-.8l-.4-.5-.4-.6-.5-.1s-.3 0-.5.2c-.1.2-.4.3-.7.4-.1 0-.2.1-.2.1l-3.9-3.3L10 7.3 8.1 4.5H4l-.5 2.8-.8-.7c-.2-.1-.4-.1-.5.1-.2.1-.2.4 0 .5l1.5 1.3-1 1.1.1 3.7-.9 3.6c-.1.4.1.9.5 1h.2c.3 0 .7-.2.8-.6l1-3.8.2-2.9 2 2.4-1.9 3.6c-.2.4-.1.9.3 1.1.1.1.2.1.4.1.3 0 .5-.2.7-.4l2.4-4.5-1-1.2 3.9 3.3-.3.4c.1 0-.5.2-.7.3zM7 10.2l-.8-.7 1.5-.7-.7 1.4zM5 5.9L6 6 4.7 7.4 5 5.9z"/></svg>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class IconHimConstructionComponent extends IconBase {
  constructor() {
    super({ viewBox: '0 0 20 20' });
  }
}

@NgModule({
  declarations: [IconHimConstructionComponent],
  exports: [IconHimConstructionComponent],
})
export class IconHimConstructionModule { }
