/*
 * Don't delete this file, it's autogenerated by the ACL icons build script
 */
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

import { IconBase } from '../../icon-base';

/** @deprecated Use `sbb-angular-icons` instead. */
@Component({
  selector: 'sbb-icon-service-vl',
  // tslint:disable-next-line
  template: `<svg [attr.class]="'sbb-svg-icon ' + svgClass" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 19 13"><path d="M0 0h2.6l1.2 10.1L9.3 0h2.8L4.8 13H1.7M13.6 0h2.6l-2.3 11H19l-.4 2h-7.7"/></svg>`,
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconServiceVlComponent extends IconBase {
  constructor() {
    super({ width: '19px', height: '13px', ratio: 1.4615384615384615 });
  }
}

/** @deprecated Use `sbb-angular-icons` instead. */
@NgModule({
  declarations: [IconServiceVlComponent],
  exports: [IconServiceVlComponent]
})
export class IconServiceVlModule {}
