/*
 * Don't delete this file, it's autogenerated by the ACL icons build script
 */
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

import { IconBase } from '../../icon-base';

@Component({
  selector: 'sbb-icon-service-fa',
  // tslint:disable-next-line:max-line-length
  template: `<svg [attr.class]="'sbb-svg-icon ' + svgClass" [attr.viewBox]="viewBox" [attr.preserveAspectRatio]="preserveAspectRatio" [attr.width]="width" [attr.height]="height" xmlns="http://www.w3.org/2000/svg"><path d="M2.7 0h7.2l-.4 2H4.9l-.7 3.3h4.3l-.4 2H3.8L2.6 13H0m13.2-5h4l-.8-5.7h-.1L13.2 8zm2.2-8h2.9l2.4 13H18l-.4-3H12l-1.7 3H7.5l7.9-13z"/></svg>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class IconServiceFaComponent extends IconBase {
  constructor() {
    super({ viewBox: '0 0 21 13', width: '21', height: '13' });
  }
}

@NgModule({
  declarations: [IconServiceFaComponent],
  exports: [IconServiceFaComponent],
})
export class IconServiceFaModule { }
