/*
 * Don't delete this file, it's autogenerated by the ACL icons build script
 */
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

import { IconBase } from '../../icon-base';

@Component({
  selector: 'sbb-icon-service-x',
  // tslint:disable-next-line:max-line-length
  template: `<svg [attr.class]="'sbb-svg-icon ' + svgClass" [attr.viewBox]="viewBox" [attr.preserveAspectRatio]="preserveAspectRatio" [attr.width]="width" [attr.height]="height" xmlns="http://www.w3.org/2000/svg"><path d="M6 0l1.9 4.5L11.5 0h3.1L9.2 6.2l3 6.8H9.3l-2-5.2L3.2 13H0l6-7.1L3.2 0"/></svg>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class IconServiceXComponent extends IconBase {
  constructor() {
    super({ viewBox: '0 0 15 13', width: '15', height: '13' });
  }
}

@NgModule({
  declarations: [IconServiceXComponent],
  exports: [IconServiceXComponent],
})
export class IconServiceXModule { }
