/*
 * Don't delete this file, it's autogenerated by the ACL icons build script
 */
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

import { IconBase } from '../../icon-base';

@Component({
  selector: 'sbb-icon-service-pa',
  // tslint:disable-next-line:max-line-length
  template: `<svg [attr.class]="'sbb-svg-icon ' + svgClass" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 13"><path d="M7.6 0l7.6 13H0L7.6 0zm5 11.7l-1.9-3.2H4.6l-1.9 3.2h9.9z"/></svg>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class IconServicePaComponent extends IconBase {
  constructor() {
    super({ width: '16px', height: '13px', ratio: 1.2307692307692308 });
  }
}

@NgModule({
  declarations: [IconServicePaComponent],
  exports: [IconServicePaComponent],
})
export class IconServicePaModule { }
