/*
 * Don't delete this file, it's autogenerated by the ACL icons build script
 */
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

import { IconBase } from '../../icon-base';

/** @deprecated Use `sbb-angular-icons` instead. */
@Component({
  selector: 'sbb-icon-service-rb',
  // tslint:disable-next-line:max-line-length
  template: `<svg [attr.class]="'sbb-svg-icon ' + svgClass" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 22 13"><path d="M4.2 5.6h.9c1.4 0 3.1-.4 3.1-2.1C8.3 2 7.1 2 6 2H4.9l-.7 3.6zM2.7 0h3.1C8.2 0 11 0 11 3.1c0 2.2-1.7 3.4-3.8 3.5.7 0 1.2.5 1.3 1.2L9.7 13H7l-.6-3.1c-.3-1.3-.3-2.3-1.7-2.3h-1L2.6 13H0L2.7 0zm12.8 5.3h1c1.3 0 2.8-.4 2.8-1.9 0-1.2-1.2-1.3-2.2-1.3h-.9l-.7 3.2zM14.3 11h.9c1.6 0 3.4-.2 3.4-2.2 0-1.4-1.3-1.6-2.7-1.6h-.8l-.8 3.8zm-.2-11H18c2 0 3.9.7 3.9 3.1 0 1.6-1.3 2.8-2.8 3.1 1.5.2 2.1 1.3 2.1 2.7 0 3.7-4.2 4-6.1 4h-3.7L14.1 0z"/></svg>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class IconServiceRbComponent extends IconBase {
  constructor() {
    super({ width: '22px', height: '13px', ratio: 1.6923076923076923 });
  }
}

/** @deprecated Use `sbb-angular-icons` instead. */
@NgModule({
  declarations: [IconServiceRbComponent],
  exports: [IconServiceRbComponent],
})
export class IconServiceRbModule { }
