/*
 * Don't delete this file, it's autogenerated by the ACL icons build script
 */
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

import { IconBase } from '../../icon-base';

/** @deprecated Use `sbb-angular-icons` instead. */
@Component({
  selector: 'sbb-icon-service-re',
  // tslint:disable-next-line
  template: `<svg [attr.class]="'sbb-svg-icon ' + svgClass" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 22 13"><path d="M4.2 5.5h.9c1.4 0 3.1-.4 3.1-2.1C8.3 2 7.1 2 6 2H4.9l-.7 3.5zM2.7 0h3.1C8.2 0 11 0 11 3.1c0 2.2-1.7 3.4-3.8 3.5.7 0 1.2.5 1.3 1.2L9.7 13H7l-.6-3.1c-.3-1.3-.3-2.3-1.7-2.3h-1L2.6 13H0L2.7 0zm11.6 0H22l-.4 2h-5.1l-.7 3.2h4.5l-.4 2h-4.6l-.7 3.8h5.1l-.4 2h-7.7"/></svg>`,
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconServiceReComponent extends IconBase {
  constructor() {
    super({ width: '22px', height: '13px', ratio: 1.6923076923076923 });
  }
}

/** @deprecated Use `sbb-angular-icons` instead. */
@NgModule({
  declarations: [IconServiceReComponent],
  exports: [IconServiceReComponent]
})
export class IconServiceReModule {}
