/*
 * Don't delete this file, it's autogenerated by the ACL icons build script
 */
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

import { IconBase } from '../../icon-base';

@Component({
  selector: 'sbb-icon-service-vr',
  // tslint:disable-next-line:max-line-length
  template: `<svg [attr.class]="'sbb-svg-icon ' + svgClass" [attr.viewBox]="viewBox" [attr.preserveAspectRatio]="preserveAspectRatio" [attr.width]="width" [attr.height]="height" xmlns="http://www.w3.org/2000/svg"><path d="M6.3 3.7h-1v-.6h2.4v.6H7l.2.4h3.7l-.3-.8H9.5v-.6H11l1.3 2.7c.1 0 .3-.1.4-.1h.4c.7 0 1.3.2 1.8.7.5.5.7 1.1.7 1.7 0 .7-.2 1.3-.7 1.7-.5.5-1.1.7-1.8.7s-1.3-.2-1.7-.7c-.5-.5-.7-1.1-.7-1.7 0-.4.1-.8.3-1.2.2-.4.5-.7.8-.9l-.2-.5-2.7 3H7.4c-.1.7-.3 1.2-.8 1.6-.5.4-1 .6-1.6.6-.7 0-1.3-.2-1.7-.7-.5-.5-.8-1.1-.8-1.8s.2-1.3.7-1.7c.5-.5 1.1-.8 1.8-.8.2 0 .5.1.8.2l.8-1.2c.1 0-.3-.6-.3-.6zM5 6c-.5 0-1 .2-1.3.5-.4.4-.5.8-.5 1.3s.2.9.5 1.3.8.5 1.3.5c.4 0 .8-.1 1.2-.4.3-.3.5-.6.6-1.1h-2l-.3-.6 1-1.5H5zm.3 1.5h1.5l-.1-.4c-.2-.3-.4-.6-.7-.8l-.7 1.2zM7 6.4c.1.2.2.3.3.5.1.1.1.3.1.6h.9L7 4.9l-.6.9c.1.1.3.2.4.3.1.1.2.2.2.3zm.6-1.7l1.3 2.6 2.3-2.6H7.6zm3.6 3.1c0 .5.2.9.5 1.3.4.4.8.5 1.3.5s.9-.2 1.3-.5c.4-.4.5-.8.5-1.3s-.2-.9-.5-1.3C14 6.2 13.6 6 13 6h-.2s-.1 0-.2.1l.9 1.9-.6.3-.9-2c-.5.4-.8.9-.8 1.5z"/><path d="M0 0h18.1v13H0V0zm1.2 11.8h15.6V1.2H1.2v10.6z"/></svg>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class IconServiceVrComponent extends IconBase {
  constructor() {
    super({ viewBox: '0 0 19 13', width: '19', height: '13' });
  }
}

@NgModule({
  declarations: [IconServiceVrComponent],
  exports: [IconServiceVrComponent],
})
export class IconServiceVrModule { }
