/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

@Component({
  selector: 'svg[sbbIconCloudLightningMoonSmall]',
  template: `
    <svg:path
      fill="none"
      stroke="#000"
      d="M15 14.5c3.313 0 3.2-4.3.7-4.2 1.1-3.7-3.8-5.4-5.3-2-1.32-1.082-3.432-.042-3.2 1.9-2.141 0-2.567 4.3.8 4.3m9.375-2.996C18.636 11.9 21.51 11.208 22.5 9c-4.168 1.762-6.956-2.354-5.518-5.2-1.089.326-1.913 1-2.528 3.034M13 13.5L10.5 16h2.169l-3.33 2.715L11 16.5H8.5l3-3H13z"
    />
  `,
  styles: [
    `
      :host-context(.sbb-icon-fixed-size) {
        width: 24px;
        height: 24px;
      }
      :host-context(.sbb-icon-inherit-color) [fill]:not([fill='none']) {
        fill: currentColor;
      }
      :host-context(.sbb-icon-inherit-color) [stroke]:not([stroke='none']) {
        stroke: currentColor;
      }
    `
  ],
  host: {
    xmlns: 'http://www.w3.org/2000/svg',
    viewBox: '0 0 24 24',
    class: 'sbb-icon sbb-icon-kom sbb-icon-weather',
    focusable: 'false'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SvgIconCloudLightningMoonSmall {}

@Component({
  selector: 'sbb-icon-cloud-lightning-moon-small',
  template: `
    <svg sbbIconCloudLightningMoonSmall></svg>
  `,
  host: {
    class: 'sbb-icon-wrapper'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconCloudLightningMoonSmall {}

@NgModule({
  declarations: [SvgIconCloudLightningMoonSmall, IconCloudLightningMoonSmall],
  exports: [SvgIconCloudLightningMoonSmall, IconCloudLightningMoonSmall]
})
export class IconCloudLightningMoonSmallModule {}
