/*
 * Don't delete this file, it's autogenerated by the ACL icons build script
 */
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

import { IconBase } from '../../icon-base';

/** @deprecated Use `@sbb-esta/angular-icons` instead. */
@Component({
  selector: 'sbb-icon-realtime-alternative',
  // tslint:disable-next-line
  template: `<svg [attr.class]="'sbb-svg-icon ' + svgClass" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M12.988 2.5h-1.875v10.396H7.227l2.155-2.156-1.326-1.325-4.42 4.421 4.42 4.422 1.326-1.326-2.16-2.16h5.766"/></svg>`,
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconRealtimeAlternativeComponent extends IconBase {
  constructor() {
    super({ width: '20px', height: '20px', ratio: 1 });
  }
}

/** @deprecated Use `@sbb-esta/angular-icons` instead. */
@NgModule({
  declarations: [IconRealtimeAlternativeComponent],
  exports: [IconRealtimeAlternativeComponent]
})
export class IconRealtimeAlternativeModule {}
