
/*
* Don't delete this file, it's autogenerated by the ACL icons build script
*/
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { IconOevBT02Component } from './sbb-icon-oev-b-t02.component';
import { IconOevBT04Component } from './sbb-icon-oev-b-t04.component';
import { IconOevBT06Component } from './sbb-icon-oev-b-t06.component';
import { IconOevBT10Component } from './sbb-icon-oev-b-t10.component';
import { IconOevBT12Component } from './sbb-icon-oev-b-t12.component';
import { IconOevBT21Component } from './sbb-icon-oev-b-t21.component';
import { IconOevBT22Component } from './sbb-icon-oev-b-t22.component';
import { IconOevBT23Component } from './sbb-icon-oev-b-t23.component';
import { IconOevBT25Component } from './sbb-icon-oev-b-t25.component';
import { IconOevBT29Component } from './sbb-icon-oev-b-t29.component';

@NgModule({
  imports: [ CommonModule ],
  // tslint:disable-next-line:max-line-length
  declarations: [IconOevBT02Component, IconOevBT04Component, IconOevBT06Component, IconOevBT10Component, IconOevBT12Component, IconOevBT21Component, IconOevBT22Component, IconOevBT23Component, IconOevBT25Component, IconOevBT29Component],
  // tslint:disable-next-line:max-line-length
  exports: [IconOevBT02Component, IconOevBT04Component, IconOevBT06Component, IconOevBT10Component, IconOevBT12Component, IconOevBT21Component, IconOevBT22Component, IconOevBT23Component, IconOevBT25Component, IconOevBT29Component],
  // tslint:disable-next-line:max-line-length
  entryComponents: [IconOevBT02Component, IconOevBT04Component, IconOevBT06Component, IconOevBT10Component, IconOevBT12Component, IconOevBT21Component, IconOevBT22Component, IconOevBT23Component, IconOevBT25Component, IconOevBT29Component]
})
export class IconOevModule { }
