/*
 * Don't delete this file, it's autogenerated by the ACL icons build script
 */
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

import { IconBase } from '../icon-base';

@Component({
  selector: 'sbb-icon-minus',
  // tslint:disable-next-line:max-line-length
  template: `<svg [attr.class]="'sbb-svg-icon ' + svgClass" [attr.viewBox]="viewBox" [attr.preserveAspectRatio]="preserveAspectRatio" [attr.width]="width" [attr.height]="height" xmlns="http://www.w3.org/2000/svg"><path d="M20 12.5H4v-1h16v1z"/></svg>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class IconMinusComponent extends IconBase {
  constructor() {
    super({ viewBox: '0 0 24 24', width: '24', height: '24' });
  }
}

@NgModule({
  declarations: [IconMinusComponent],
  exports: [IconMinusComponent],
})
export class IconMinusModule { }
