/*
 * Don't delete this file, it's autogenerated by the ACL icons build script
 */
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

import { IconBase } from '../icon-base';

@Component({
  selector: 'sbb-icon-swap',
  // tslint:disable-next-line:max-line-length
  template: `<svg [attr.class]="'sbb-svg-icon ' + svgClass" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M21.4 16.4l-3.8 3.9-3.9-3.9.7-.7 2.6 2.6v-11c0-1.2-1-2.2-2.2-2.2s-2.2 1-2.2 2.2v9.4c0 1.8-1.5 3.2-3.2 3.2S6 18.5 6 16.7v-11L3.4 8.4l-.8-.8 3.8-3.9 3.9 3.9-.7.8L7 5.7v11c0 1.2 1 2.2 2.2 2.2s2.2-1 2.2-2.2V7.3c0-1.8 1.5-3.2 3.2-3.2S18 5.5 18 7.3v11l2.6-2.7.8.8z"/></svg>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class IconSwapComponent extends IconBase {
  constructor() {
    super({ width: '24px', height: '24px', ratio: 1 });
  }
}

@NgModule({
  declarations: [IconSwapComponent],
  exports: [IconSwapComponent],
})
export class IconSwapModule { }
