/*
 * Don't delete this file, it's autogenerated by the ACL icons build script
 */
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

import { IconBase } from '../icon-base';

@Component({
  selector: 'sbb-icon-search',
  // tslint:disable-next-line:max-line-length
  template: `<svg [attr.class]="'sbb-svg-icon ' + svgClass" [attr.viewBox]="viewBox" [attr.preserveAspectRatio]="preserveAspectRatio" [attr.width]="width" [attr.height]="height" xmlns="http://www.w3.org/2000/svg"><path d="M20.4 19.6l-6.8-6.8c.9-1 1.4-2.4 1.4-3.9 0-3.3-2.7-6-6-6S3 5.7 3 9s2.7 6 6 6c1.5 0 2.8-.5 3.9-1.4l6.8 6.8.7-.8zM9 14c-2.8 0-5-2.2-5-5s2.2-5 5-5 5 2.2 5 5-2.2 5-5 5z"/></svg>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class IconSearchComponent extends IconBase {
  constructor() {
    super({ viewBox: '0 0 24 24' });
  }
}

@NgModule({
  declarations: [IconSearchComponent],
  exports: [IconSearchComponent],
})
export class IconSearchModule { }
