export { TabGroupAsyncExample } from './tab-group-async/tab-group-async-example';
export { TabGroupBadgeExample } from './tab-group-badge/tab-group-badge-example';
export { TabGroupBasicExample } from './tab-group-basic/tab-group-basic-example';
export { TabGroupCustomLabelExample } from './tab-group-custom-label/tab-group-custom-label-example';
export { TabGroupDynamicHeightExample } from './tab-group-dynamic-height/tab-group-dynamic-height-example';
export { TabGroupDynamicExample } from './tab-group-dynamic/tab-group-dynamic-example';
export { TabGroupLazyLoadedExample } from './tab-group-lazy-loaded/tab-group-lazy-loaded-example';
export { TabGroupPreserveContentExample } from './tab-group-preserve-content/tab-group-preserve-content-example';
export { TabNavBarBasicExample } from './tab-nav-bar-basic/tab-nav-bar-basic-example';
