/*
 * Don't delete this file, it's autogenerated by the ACL icons build script
 */
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

import { IconBase } from '../icon-base';

/** @deprecated Use `sbb-angular-icons` instead. */
@Component({
  selector: 'sbb-icon-lh-railplus',
  // tslint:disable-next-line
  template: `<svg [attr.class]="'sbb-svg-icon ' + svgClass" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 407 99"><path fill="#ED1C24" d="M16.3.4L406.6.3l-16.2 98.4-390-.1L16.3.4"/><path fill="#FFF" fill-rule="evenodd" d="M29.1 82h8.6l5-31.8h.2L49.6 82h9l-7-31.7C59 49 62.3 39.7 63.2 33.6 65.8 17.3 56 17 49.7 17H39.4L29.1 82zm14.3-36.2l3.4-21.5h1.4c6.6-.2 6.5 5 5.6 11.2-1.1 6.6-4 10.7-10.4 10.3zM87 17L62.6 82H71l4.4-12.7h12.9l.5 12.7h8.7l-3.7-65H87zm1.2 45.6H77.8l10.4-33h.2l-.5 23.6.3 9.4z" clip-rule="evenodd"/><path fill="#FFF" d="M124.7 17h-8.6l-10.3 65h8.6l10.3-65m13.1 0l-10.3 65h23.1l1.2-7.5h-14.5l9.1-57.5h-8.6"/><path fill="#FFF" fill-rule="evenodd" d="M248.2 82l4.6-28.8c13.4.5 19.5-5.6 21.6-18.8C277 17.7 267.6 17 260.2 17h-10.4l-10.3 65h8.7zm10.3-57.7c6.6 0 7.5 4.9 6.6 10.8-1.1 7.2-3.9 11.3-11.2 10.8l3.4-21.6h1.2z" clip-rule="evenodd"/><path fill="#FFF" d="M285.9 17l-10.3 65h23.1l1.2-7.5h-14.5l9.1-57.5h-8.6m31.1 0l-7.1 44.9c-1.9 11.7-2.1 21 11.6 21 15 0 16.7-11.2 18-19.8l7.3-46.1h-8.6l-7.7 48.6c-.9 5.3-2.1 9.1-8 9.1-3.5 0-5.8-1.7-4.4-10.1l7.6-47.7H317v.1zm62.8 1.3c-2.5-1.6-5.5-2.2-8.8-2.2-9.7 0-15.8 7.5-17.2 16.6-2.7 17.1 15.1 19.7 13 32.6-.8 4.8-3.7 9.1-9 9.1-3.4 0-5.7-1.5-8-3.4l-1.4 8.7c2.3 2.2 5.6 3.1 9 3.1 9.6 0 16.5-7.8 18-17 1.4-8.8-1.3-13.1-6.2-19.1l-5.4-7.2c-1.4-2.2-1.7-4.2-1.3-7.1.7-4.5 4.3-8.4 9-8.4 2.9 0 4.9 1.1 6.9 2.8l1.4-8.5z"/><circle cx="194.2" cy="49.9" r="33.9"/><path fill="#FCAF17" d="M163.4 49.9c0-17 13.8-30.8 30.8-30.8S225 32.9 225 49.9s-13.8 30.8-30.8 30.8c-17 .1-30.8-13.7-30.8-30.8z"/><path d="M175.2 46.4v6.9H191v15.8h6.9V53.3h15.9v-6.9h-15.9V30.5H191v15.9h-15.8"/></svg>`,
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconLhRailplusComponent extends IconBase {
  constructor() {
    super({ width: '407px', height: '99px', ratio: 4.111111111111111 });
  }
}

/** @deprecated Use `sbb-angular-icons` instead. */
@NgModule({
  declarations: [IconLhRailplusComponent],
  exports: [IconLhRailplusComponent]
})
export class IconLhRailplusModule {}
