/*
 * Don't delete this file, it's autogenerated by the ACL icons build script
 */
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

import { IconBase } from '../icon-base';

/** @deprecated Use `sbb-angular-icons` instead. */
@Component({
  selector: 'sbb-icon-lh-concerts-musicals-festivals',
  // tslint:disable-next-line
  template: `<svg [attr.class]="'sbb-svg-icon ' + svgClass" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48"><path fill="none" stroke="#000" stroke-miterlimit="10" d="M16.499 26.5v-2.536a5.979 5.979 0 0 0 2-4.464V12a1.5 1.5 0 1 0-3 0v7h0v-2a1.5 1.5 0 1 0-3 0v2h0v-2a1.5 1.5 0 1 0-3 0v2-7a1.5 1.5 0 1 0-3 0v7.5c0 1.776.775 3.366 2 4.464V26.5m9 10.924l-10 .076v-11h10zm-10-8.924h10m-8 2.5v6.5" vector-effect="non-scaling-stroke"/><circle cx="25.001" cy="33" r="3.5" fill="none" stroke="#000" stroke-miterlimit="10" vector-effect="non-scaling-stroke"/><circle cx="38.002" cy="29" r="3.5" fill="none" stroke="#000" stroke-miterlimit="10" vector-effect="non-scaling-stroke"/><path fill="none" stroke="#000" stroke-miterlimit="10" d="M28.501 33V15.443l13-2.943v16.81m-13-10.867l13-2.943" vector-effect="non-scaling-stroke"/></svg>`,
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconLhConcertsMusicalsFestivalsComponent extends IconBase {
  constructor() {
    super({ width: '48px', height: '48px', ratio: 1 });
  }
}

/** @deprecated Use `sbb-angular-icons` instead. */
@NgModule({
  declarations: [IconLhConcertsMusicalsFestivalsComponent],
  exports: [IconLhConcertsMusicalsFestivalsComponent]
})
export class IconLhConcertsMusicalsFestivalsModule {}
