import { Thumbnail } from './thumbnail';
import { Type } from '@angular/core';

export class UiComponent {
    constructor(
        public id: string,
        public routerLink: string,
        public title: string,
        public subTitle: string,
        public isComponent: Boolean,
        public isDirective: Boolean,
        public authors: string[],
        public description: string,
        public source: string,
        public importText: string,
        public gettingStartedText: string,
        public modelBindingText: string,
        public iconsText: string,
        public autoResizeText: string,
        public propertiesText: string,
        public eventsText: string,
        public stylingText: string,
        public dependenciesText: string,
        public importCode: string,
        public gettingStartedCode: string,
        public modelBindingCode: string,
        public iconsCode: string,
        public autoResizeCode: string,
        public propertiesCode: string,
        public eventsCode: string,
        public stylingCode: string,
        public dependenciesCode: string,
        public component?: Type<{}>,
        public thumbnails?: Thumbnail[],
        public showImport: boolean = true,
        public showGettingStarted: boolean = true,
        public showModelBinding: boolean = true,
        public showIcons: boolean = true,
        public showAutoResize: boolean = true,
        public showProperties: boolean = true,
        public showEvents: boolean = true,
        public showStyling: boolean = true,
        public showDependencies: boolean = true
    ) { }
}
