/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

@Component({
  selector: 'svg[sbbIconPowerPlugMedium]',
  template: `
    <svg:path
      fill="none"
      stroke="#000"
      d="M9.75 11.25h18V18c0 3.04-2.488 5.25-5.25 5.25H15c-3.117 0-5.25-2.622-5.25-5.25v-6.75zm3-6.75v6.75m12-6.75v6.75m-9 12v4.5h6v-4.5m-3 8.25v-3.75"
    />
  `,
  styles: [
    `
      :host-context(.sbb-icon-fixed-size) {
        width: 36px;
        height: 36px;
      }
      :host-context(.sbb-icon-inherit-color) [fill]:not([fill='none']) {
        fill: currentColor;
      }
      :host-context(.sbb-icon-inherit-color) [stroke]:not([stroke='none']) {
        stroke: currentColor;
      }
    `
  ],
  host: {
    xmlns: 'http://www.w3.org/2000/svg',
    viewBox: '0 0 36 36',
    class: 'sbb-icon sbb-icon-kom sbb-icon-hardware',
    focusable: 'false'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SvgIconPowerPlugMedium {}

@Component({
  selector: 'sbb-icon-power-plug-medium',
  template: `
    <svg sbbIconPowerPlugMedium></svg>
  `,
  host: {
    class: 'sbb-icon-wrapper'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconPowerPlugMedium {}

@NgModule({
  declarations: [SvgIconPowerPlugMedium, IconPowerPlugMedium],
  exports: [SvgIconPowerPlugMedium, IconPowerPlugMedium]
})
export class IconPowerPlugMediumModule {}
