/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

@Component({
  selector: 'svg[sbbIconPrinterMedium]',
  template: `
    <svg:path
      fill="none"
      stroke="#000"
      d="M12 29.25h12m-12-3h12m-12-3h12m-14.25 9h16.5v-12H9.75v12zm0-7.5h-6v-13.5h28.5v13.5h-6m-16.5-13.5v-6h16.5v6"
    />
  `,
  styles: [
    `
      :host-context(.sbb-icon-fixed-size) {
        width: 36px;
        height: 36px;
      }
      :host-context(.sbb-icon-inherit-color) [fill]:not([fill='none']) {
        fill: currentColor;
      }
      :host-context(.sbb-icon-inherit-color) [stroke]:not([stroke='none']) {
        stroke: currentColor;
      }
    `
  ],
  host: {
    xmlns: 'http://www.w3.org/2000/svg',
    viewBox: '0 0 36 36',
    class: 'sbb-icon sbb-icon-kom sbb-icon-hardware',
    focusable: 'false'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SvgIconPrinterMedium {}

@Component({
  selector: 'sbb-icon-printer-medium',
  template: `
    <svg sbbIconPrinterMedium></svg>
  `,
  host: {
    class: 'sbb-icon-wrapper'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconPrinterMedium {}

@NgModule({
  declarations: [SvgIconPrinterMedium, IconPrinterMedium],
  exports: [SvgIconPrinterMedium, IconPrinterMedium]
})
export class IconPrinterMediumModule {}
