
/*
* Don't delete this file, it's autogenerated by the ACL icons build script
*/
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { IconLhAdventurePanoramaTripsComponent } from './sbb-icon-lh-adventure-panorama-trips.component';
import { IconLhArtCultureMuseumsComponent } from './sbb-icon-lh-art-culture-museums.component';
import { IconLhBikeEbikeComponent } from './sbb-icon-lh-bike-ebike.component';
import { IconLhChristmasMarketsShoppingComponent } from './sbb-icon-lh-christmas-markets-shopping.component';
import { IconLhCityTripsComponent } from './sbb-icon-lh-city-trips.component';
import { IconLhConcertsMusicalsFestivalsComponent } from './sbb-icon-lh-concerts-musicals-festivals.component';
import { IconLhDiscountComponent } from './sbb-icon-lh-discount.component';
import { IconLhFamilyExcursionsComponent } from './sbb-icon-lh-family-excursions.component';
import { IconLhGamesFunComponent } from './sbb-icon-lh-games-fun.component';
import { IconLhGroupExcursionsComponent } from './sbb-icon-lh-group-excursions.component';
import { IconLhHikingComponent } from './sbb-icon-lh-hiking.component';
import { IconLhInterrailComponent } from './sbb-icon-lh-interrail.component';
import { IconLhMarketsShoppingComponent } from './sbb-icon-lh-markets-shopping.component';
import { IconLhMountainsViewsComponent } from './sbb-icon-lh-mountains-views.component';
import { IconLhNatureSightsOfInterestComponent } from './sbb-icon-lh-nature-sights-of-interest.component';
import { IconLhRailplusComponent } from './sbb-icon-lh-railplus.component';
import { IconLhRailBoatComponent } from './sbb-icon-lh-rail-boat.component';
import { IconLhSchoolExcursionsComponent } from './sbb-icon-lh-school-excursions.component';
import { IconLhShortTripsInSwitzerlandComponent } from './sbb-icon-lh-short-trips-in-switzerland.component';
import { IconLhSnowNRailComponent } from './sbb-icon-lh-snow-n-rail.component';
import { IconLhSportsEventsComponent } from './sbb-icon-lh-sports-events.component';
import { IconLhTobogganingWinterHikingComponent } from './sbb-icon-lh-tobogganing-winter-hiking.component';
import { IconLhTradeFairsFolkFestivalsComponent } from './sbb-icon-lh-trade-fairs-folk-festivals.component';
import { IconLhWellnessRelaxationComponent } from './sbb-icon-lh-wellness-relaxation.component';
import { IconLhZooAnimalParksComponent } from './sbb-icon-lh-zoo-animal-parks.component';

@NgModule({
  imports: [ CommonModule ],
  // tslint:disable-next-line:max-line-length
  declarations: [IconLhAdventurePanoramaTripsComponent, IconLhArtCultureMuseumsComponent, IconLhBikeEbikeComponent, IconLhChristmasMarketsShoppingComponent, IconLhCityTripsComponent, IconLhConcertsMusicalsFestivalsComponent, IconLhDiscountComponent, IconLhFamilyExcursionsComponent, IconLhGamesFunComponent, IconLhGroupExcursionsComponent, IconLhHikingComponent, IconLhInterrailComponent, IconLhMarketsShoppingComponent, IconLhMountainsViewsComponent, IconLhNatureSightsOfInterestComponent, IconLhRailplusComponent, IconLhRailBoatComponent, IconLhSchoolExcursionsComponent, IconLhShortTripsInSwitzerlandComponent, IconLhSnowNRailComponent, IconLhSportsEventsComponent, IconLhTobogganingWinterHikingComponent, IconLhTradeFairsFolkFestivalsComponent, IconLhWellnessRelaxationComponent, IconLhZooAnimalParksComponent],
  // tslint:disable-next-line:max-line-length
  exports: [IconLhAdventurePanoramaTripsComponent, IconLhArtCultureMuseumsComponent, IconLhBikeEbikeComponent, IconLhChristmasMarketsShoppingComponent, IconLhCityTripsComponent, IconLhConcertsMusicalsFestivalsComponent, IconLhDiscountComponent, IconLhFamilyExcursionsComponent, IconLhGamesFunComponent, IconLhGroupExcursionsComponent, IconLhHikingComponent, IconLhInterrailComponent, IconLhMarketsShoppingComponent, IconLhMountainsViewsComponent, IconLhNatureSightsOfInterestComponent, IconLhRailplusComponent, IconLhRailBoatComponent, IconLhSchoolExcursionsComponent, IconLhShortTripsInSwitzerlandComponent, IconLhSnowNRailComponent, IconLhSportsEventsComponent, IconLhTobogganingWinterHikingComponent, IconLhTradeFairsFolkFestivalsComponent, IconLhWellnessRelaxationComponent, IconLhZooAnimalParksComponent]
})
export class IconLeisureHolidaysModule { }
