/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

@Component({
  selector: 'svg[sbbIconEyeDisabledSmall]',
  template: `
    <svg:path
      fill="none"
      stroke="#000"
      d="M9.085 10.085C8.693 10.647 8.5 11.263 8.5 12A3.5 3.5 0 0012 15.5c.725 0 1.358-.204 1.915-.585m1.467-2.058c.069-.276.118-.56.118-.856A3.5 3.5 0 0012 8.5a3.5 3.5 0 00-.856.117M4 5l15 15m-1.343-4.91A17.304 17.304 0 0020.5 12c-.744-1.1-4.25-5.5-8.5-5.5-.86 0-1.684.182-2.46.473m-2.317 1.25C5.345 9.559 3.993 11.298 3.5 12c.744 1.1 4.25 5.5 8.5 5.5 1.273 0 2.466-.388 3.539-.961"
    />
  `,
  styles: [
    `
      :host-context(.sbb-icon-fixed-size) {
        width: 24px;
        height: 24px;
      }
      :host-context(.sbb-icon-inherit-color) [fill]:not([fill='none']) {
        fill: currentColor;
      }
      :host-context(.sbb-icon-inherit-color) [stroke]:not([stroke='none']) {
        stroke: currentColor;
      }
    `
  ],
  host: {
    xmlns: 'http://www.w3.org/2000/svg',
    viewBox: '0 0 24 24',
    class: 'sbb-icon sbb-icon-kom sbb-icon-status',
    focusable: 'false'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SvgIconEyeDisabledSmall {}

@Component({
  selector: 'sbb-icon-eye-disabled-small',
  template: `
    <svg sbbIconEyeDisabledSmall></svg>
  `,
  host: {
    class: 'sbb-icon-wrapper'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconEyeDisabledSmall {}

@NgModule({
  declarations: [SvgIconEyeDisabledSmall, IconEyeDisabledSmall],
  exports: [SvgIconEyeDisabledSmall, IconEyeDisabledSmall]
})
export class IconEyeDisabledSmallModule {}
