/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

@Component({
  selector: 'svg[sbbIconTickClipboardMedium]',
  template: `
    <svg:path
      fill="none"
      stroke="#000"
      d="M5.25 5.25v27h25.5v-27h-9v-1.5h-7.5v1.5h-9zm16.5 0v1.5h-7.5v-1.5M9 21l6 4.875L25.5 12"
    />
  `,
  styles: [
    `
      :host-context(.sbb-icon-fixed-size) {
        width: 36px;
        height: 36px;
      }
      :host-context(.sbb-icon-inherit-color) [fill]:not([fill='none']) {
        fill: currentColor;
      }
      :host-context(.sbb-icon-inherit-color) [stroke]:not([stroke='none']) {
        stroke: currentColor;
      }
    `
  ],
  host: {
    xmlns: 'http://www.w3.org/2000/svg',
    viewBox: '0 0 36 36',
    class: 'sbb-icon sbb-icon-kom sbb-icon-status',
    focusable: 'false'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SvgIconTickClipboardMedium {}

@Component({
  selector: 'sbb-icon-tick-clipboard-medium',
  template: `
    <svg sbbIconTickClipboardMedium></svg>
  `,
  host: {
    class: 'sbb-icon-wrapper'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconTickClipboardMedium {}

@NgModule({
  declarations: [SvgIconTickClipboardMedium, IconTickClipboardMedium],
  exports: [SvgIconTickClipboardMedium, IconTickClipboardMedium]
})
export class IconTickClipboardMediumModule {}
