/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable

export * from './railway-switch-large';
export * from './train-signal-large';
export * from './train-tracks-large';
export * from './construction-medium';
export * from './railway-switch-medium';
export * from './construction-small';
export * from './railway-switch-small';
