/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

@Component({
  selector: 'svg[sbbIconTicketPercentMedium]',
  template: `
    <svg:g fill="none" fill-rule="evenodd" stroke="#000">
      <svg:path
        d="M27.75 17.25c0-2.55 1.95-4.5 4.5-4.5v-6H3.75v21h28.5v-6c-2.55 0-4.5-1.95-4.5-4.5zm-15.004-5.254a2.249 2.249 0 11-4.5 0 2.25 2.25 0 114.5 0zM18.75 22.5a2.25 2.25 0 11-4.5 0 2.25 2.25 0 014.5 0zm-12 1.5l13.5-13.5"
      />
      <svg:path stroke-dasharray="1 1" d="M24.75 27V7.5" />
    </svg:g>
  `,
  styles: [
    `
      :host-context(.sbb-icon-fixed-size) {
        width: 36px;
        height: 36px;
      }
      :host-context(.sbb-icon-inherit-color) [fill]:not([fill='none']) {
        fill: currentColor;
      }
      :host-context(.sbb-icon-inherit-color) [stroke]:not([stroke='none']) {
        stroke: currentColor;
      }
    `
  ],
  host: {
    xmlns: 'http://www.w3.org/2000/svg',
    viewBox: '0 0 36 36',
    class: 'sbb-icon sbb-icon-kom sbb-icon-ticket',
    focusable: 'false'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SvgIconTicketPercentMedium {}

@Component({
  selector: 'sbb-icon-ticket-percent-medium',
  template: `
    <svg sbbIconTicketPercentMedium></svg>
  `,
  host: {
    class: 'sbb-icon-wrapper'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconTicketPercentMedium {}

@NgModule({
  declarations: [SvgIconTicketPercentMedium, IconTicketPercentMedium],
  exports: [SvgIconTicketPercentMedium, IconTicketPercentMedium]
})
export class IconTicketPercentMediumModule {}
