/*
 * Autogenerated by schematics
 */
import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

import { IconBase } from '../icon-base';

@Component({
  selector: 'sbb-icon-kaffe',
  // tslint:disable:max-line-length
  template: `<svg [attr.class]="'sbb-svg-icon ' + svgClass" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 36 36"><path fill="none" stroke="#000" d="M23.25 27.75h4.5v-9h-4.5v9zM11.25 3c0 .9.9 2.25 2.25 2.25 2.7 0 3.15 4.5 0 4.5-1.2 0-2.25.9-2.25 2.25m6-9c0 .9.9 2.25 2.25 2.25 2.7 0 3.15 4.5 0 4.5-1.2 0-2.25.9-2.25 2.25m-9 18.75h15v-16.5h-15v16.5z"/></svg>`,
  // tslint:enable:max-line-length
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class IconKaffeComponent extends IconBase {
  constructor() {
    super({ width: '24px', height: '24px', ratio: 1 });
  }
}

@NgModule({
  imports: [CommonModule],
  declarations: [IconKaffeComponent],
  exports: [IconKaffeComponent],
})
export class IconKaffeModule { }
