/*
 * Don't delete this file, it's autogenerated by the ACL icons build script
 */
import { NgModule } from '@angular/core';

import { IconEffizienz48Module } from './icon-effizienz-48.module';
import { IconEinfachheit48Module } from './icon-einfachheit-48.module';
import { IconElektroauto48Module } from './icon-elektroauto-48.module';
import { IconFlexibilitaet48Module } from './icon-flexibilitaet-48.module';
import { IconLetztemeile48Module } from './icon-letztemeile-48.module';
import { IconOev48Module } from './icon-oev-48.module';
import { IconParking48Module } from './icon-parking-48.module';
import { IconPioneering48Module } from './icon-pioneering-48.module';
import { IconSorglos48Module } from './icon-sorglos-48.module';
import { IconUmwelt48Module } from './icon-umwelt-48.module';
import { IconWallbox48Module } from './icon-wallbox-48.module';

/** @deprecated Use `@sbb-esta/angular-icons` instead. */
@NgModule({
  imports: [
    IconEffizienz48Module,
    IconEinfachheit48Module,
    IconElektroauto48Module,
    IconFlexibilitaet48Module,
    IconLetztemeile48Module,
    IconOev48Module,
    IconParking48Module,
    IconPioneering48Module,
    IconSorglos48Module,
    IconUmwelt48Module,
    IconWallbox48Module
  ],
  exports: [
    IconEffizienz48Module,
    IconEinfachheit48Module,
    IconElektroauto48Module,
    IconFlexibilitaet48Module,
    IconLetztemeile48Module,
    IconOev48Module,
    IconParking48Module,
    IconPioneering48Module,
    IconSorglos48Module,
    IconUmwelt48Module,
    IconWallbox48Module
  ]
})
export class IconCollectionCampaignsGreenclassModule {}
