/*
 * Autogenerated by schematics
 */
import {<% for (let icon of icons) { %>
  Icon<%= classify(icon.name) %>Component,<% } %>
} from './root';

export const iconComponentsMetaInformation = [<% for (let icon of icons) { %>
  {
    selector: 'sbb-icon-<%= dasherize(icon.name) %>',
    name: 'Icon<%= classify(icon.name) %>Component',
    modules: [
      'Icon<%= classify(icon.name) %>Module',<% for (let module of icon.modules) { %>
      'IconCollection<%= module %>Module',<% } %>
      'IconCollectionModule',
    ],
    sizes: [<% for (let size of icon.sizes) { %>
      '<%= size %>',<% } %>
    ],
    meta: [<% for (let meta of icon.meta) { %>
      '<%= meta %>',<% } %>
    ],
    component: Icon<%= classify(icon.name) %>Component,
  },<% } %>
];

export const iconComponentList = [<% for (let icon of icons) { %>
  Icon<%= classify(icon.name) %>Component,<% } %>
];