/*
 * Don't delete this file, it's autogenerated by the ACL icons build script
 */
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

import { IconBase } from '../icon-base';

/** @deprecated Use `sbb-angular-icons` instead. */
@Component({
  selector: 'sbb-icon-stratus',
  // tslint:disable-next-line:max-line-length
  template: `<svg [attr.class]="'sbb-svg-icon ' + svgClass" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M11 4h5v1h-5zM8 6h9v1H8zM7 8h10v1H7zM6 10h3v1H6zM10 10h9v1h-9zM7 12.005h12v1H7z"/></svg>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class IconStratusComponent extends IconBase {
  constructor() {
    super({ width: '24px', height: '24px', ratio: 1 });
  }
}

/** @deprecated Use `sbb-angular-icons` instead. */
@NgModule({
  declarations: [IconStratusComponent],
  exports: [IconStratusComponent],
})
export class IconStratusModule { }
