
/*
* Don't delete this file, it's autogenerated by the ACL icons build script
*/
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { IconGcEffizienz48Component } from './sbb-icon-gc-effizienz-48.component';
import { IconGcEinfachheit48Component } from './sbb-icon-gc-einfachheit-48.component';
import { IconGcElektroauto48Component } from './sbb-icon-gc-elektroauto-48.component';
import { IconGcFlexibilitaet48Component } from './sbb-icon-gc-flexibilitaet-48.component';
import { IconGcLetztemeile48Component } from './sbb-icon-gc-letztemeile-48.component';
import { IconGcOev48Component } from './sbb-icon-gc-oev-48.component';
import { IconGcParking48Component } from './sbb-icon-gc-parking-48.component';
import { IconGcPioneering48Component } from './sbb-icon-gc-pioneering-48.component';
import { IconGcSorglos48Component } from './sbb-icon-gc-sorglos-48.component';
import { IconGcUmwelt48Component } from './sbb-icon-gc-umwelt-48.component';
import { IconGcWallbox48Component } from './sbb-icon-gc-wallbox-48.component';

@NgModule({
  imports: [ CommonModule ],
  // tslint:disable-next-line:max-line-length
  declarations: [IconGcEffizienz48Component, IconGcEinfachheit48Component, IconGcElektroauto48Component, IconGcFlexibilitaet48Component, IconGcLetztemeile48Component, IconGcOev48Component, IconGcParking48Component, IconGcPioneering48Component, IconGcSorglos48Component, IconGcUmwelt48Component, IconGcWallbox48Component],
  // tslint:disable-next-line:max-line-length
  exports: [IconGcEffizienz48Component, IconGcEinfachheit48Component, IconGcElektroauto48Component, IconGcFlexibilitaet48Component, IconGcLetztemeile48Component, IconGcOev48Component, IconGcParking48Component, IconGcPioneering48Component, IconGcSorglos48Component, IconGcUmwelt48Component, IconGcWallbox48Component],
  // tslint:disable-next-line:max-line-length
  entryComponents: [IconGcEffizienz48Component, IconGcEinfachheit48Component, IconGcElektroauto48Component, IconGcFlexibilitaet48Component, IconGcLetztemeile48Component, IconGcOev48Component, IconGcParking48Component, IconGcPioneering48Component, IconGcSorglos48Component, IconGcUmwelt48Component, IconGcWallbox48Component]
})
export class IconGreenclassModule { }
