
/*
* Don't delete this file, it's autogenerated by the ACL icons build script
*/
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { IconSonnigComponent } from './sbb-icon-sonnig.component';
import { IconStratusComponent } from './sbb-icon-stratus.component';
import { IconMondComponent } from './sbb-icon-mond.component';
import { IconSchneeGewitterComponent } from './sbb-icon-schnee-gewitter.component';
import { IconSchneesternComponent } from './sbb-icon-schneestern.component';
import { IconBewoelktMitSonneComponent } from './sbb-icon-bewoelkt-mit-sonne.component';
import { IconWolkeMondComponent } from './sbb-icon-wolke-mond.component';
import { IconSchneeMondComponent } from './sbb-icon-schnee-mond.component';
import { IconGewitterBeiNachtComponent } from './sbb-icon-gewitter-bei-nacht.component';
import { IconRegenBeiNachtComponent } from './sbb-icon-regen-bei-nacht.component';
import { IconStarkerRegenBeiNachtComponent } from './sbb-icon-starker-regen-bei-nacht.component';
import { IconStarkerRegenMitSonneComponent } from './sbb-icon-starker-regen-mit-sonne.component';
import { IconSchneeMitSonneComponent } from './sbb-icon-schnee-mit-sonne.component';
import { IconBewoelktComponent } from './sbb-icon-bewoelkt.component';
import { IconNieselComponent } from './sbb-icon-niesel.component';
import { IconGraupelComponent } from './sbb-icon-graupel.component';
import { IconLeichtBewoelktComponent } from './sbb-icon-leicht-bewoelkt.component';
import { IconRegenMitSonneComponent } from './sbb-icon-regen-mit-sonne.component';
import { IconRegenComponent } from './sbb-icon-regen.component';
import { IconSchneeSturmComponent } from './sbb-icon-schnee-sturm.component';
import { IconSchneeComponent } from './sbb-icon-schnee.component';
import { IconGewitterComponent } from './sbb-icon-gewitter.component';
import { IconNebelComponent } from './sbb-icon-nebel.component';

@NgModule({
  imports: [ CommonModule ],
  // tslint:disable-next-line:max-line-length
  declarations: [IconSonnigComponent, IconStratusComponent, IconMondComponent, IconSchneeGewitterComponent, IconSchneesternComponent, IconBewoelktMitSonneComponent, IconWolkeMondComponent, IconSchneeMondComponent, IconGewitterBeiNachtComponent, IconRegenBeiNachtComponent, IconStarkerRegenBeiNachtComponent, IconStarkerRegenMitSonneComponent, IconSchneeMitSonneComponent, IconBewoelktComponent, IconNieselComponent, IconGraupelComponent, IconLeichtBewoelktComponent, IconRegenMitSonneComponent, IconRegenComponent, IconSchneeSturmComponent, IconSchneeComponent, IconGewitterComponent, IconNebelComponent],
  // tslint:disable-next-line:max-line-length
  exports: [IconSonnigComponent, IconStratusComponent, IconMondComponent, IconSchneeGewitterComponent, IconSchneesternComponent, IconBewoelktMitSonneComponent, IconWolkeMondComponent, IconSchneeMondComponent, IconGewitterBeiNachtComponent, IconRegenBeiNachtComponent, IconStarkerRegenBeiNachtComponent, IconStarkerRegenMitSonneComponent, IconSchneeMitSonneComponent, IconBewoelktComponent, IconNieselComponent, IconGraupelComponent, IconLeichtBewoelktComponent, IconRegenMitSonneComponent, IconRegenComponent, IconSchneeSturmComponent, IconSchneeComponent, IconGewitterComponent, IconNebelComponent],
  // tslint:disable-next-line:max-line-length
  entryComponents: [IconSonnigComponent, IconStratusComponent, IconMondComponent, IconSchneeGewitterComponent, IconSchneesternComponent, IconBewoelktMitSonneComponent, IconWolkeMondComponent, IconSchneeMondComponent, IconGewitterBeiNachtComponent, IconRegenBeiNachtComponent, IconStarkerRegenBeiNachtComponent, IconStarkerRegenMitSonneComponent, IconSchneeMitSonneComponent, IconBewoelktComponent, IconNieselComponent, IconGraupelComponent, IconLeichtBewoelktComponent, IconRegenMitSonneComponent, IconRegenComponent, IconSchneeSturmComponent, IconSchneeComponent, IconGewitterComponent, IconNebelComponent]
})
export class IconWeatherModule { }
