/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

@Component({
  selector: 'svg[sbbIconCloudIceMedium]',
  template: `
    <svg:g fill="none" fill-rule="evenodd">
      <svg:path
        stroke="#000"
        d="M10.8 15.3c-3.211 0-3.85 6.45 1.2 6.45h10.5c4.805 0 4.8-6.45 1.05-6.3 1.65-5.55-5.7-8.1-7.95-3-1.981-1.623-5.148-.063-4.8 2.85z"
      />
      <svg:path
        fill="#000"
        d="M9 25.5V24h1.5v1.5H9zm3 0V24h1.5v1.5H12zm-3 3V27h1.5v1.5H9zm1.5-1.5v-1.5H12V27h-1.5zm1.5 1.5V27h1.5v1.5H12zm3 3V30h1.5v1.5H15zm3 0V30h1.5v1.5H18zm-3 3V33h1.5v1.5H15zm1.5-1.5v-1.5H18V33h-1.5zm1.5 1.5V33h1.5v1.5H18zm3-9V24h1.5v1.5H21zm3 0V24h1.5v1.5H24zm-3 3V27h1.5v1.5H21zm1.5-1.5v-1.5H24V27h-1.5zm1.5 1.5V27h1.5v1.5H24z"
      />
    </svg:g>
  `,
  styles: [
    `
      :host-context(.sbb-icon-fixed-size) {
        width: 36px;
        height: 36px;
      }
      :host-context(.sbb-icon-inherit-color) [fill]:not([fill='none']) {
        fill: currentColor;
      }
      :host-context(.sbb-icon-inherit-color) [stroke]:not([stroke='none']) {
        stroke: currentColor;
      }
    `
  ],
  host: {
    xmlns: 'http://www.w3.org/2000/svg',
    viewBox: '0 0 36 36',
    class: 'sbb-icon sbb-icon-kom sbb-icon-weather',
    focusable: 'false'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SvgIconCloudIceMedium {}

@Component({
  selector: 'sbb-icon-cloud-ice-medium',
  template: `
    <svg sbbIconCloudIceMedium></svg>
  `,
  host: {
    class: 'sbb-icon-wrapper'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconCloudIceMedium {}

@NgModule({
  declarations: [SvgIconCloudIceMedium, IconCloudIceMedium],
  exports: [SvgIconCloudIceMedium, IconCloudIceMedium]
})
export class IconCloudIceMediumModule {}
