/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

@Component({
  selector: 'svg[sbbIconCloudDenseFogSmall]',
  template: `
    <svg:path
      fill="none"
      stroke="#000"
      d="M7.2 10.2c-.232-1.942 1.88-2.982 3.2-1.9 1.5-3.4 6.4-1.7 5.3 2 2.5-.1 2.621 4.2-.7 4.2H8c-3.367 0-2.94-4.3-.8-4.3zM5 16.5h12.993H5zm0 4h12.993H5zm1-2h10.993H6z"
    />
  `,
  styles: [
    `
      :host-context(.sbb-icon-fixed-size) {
        width: 24px;
        height: 24px;
      }
      :host-context(.sbb-icon-inherit-color) [fill]:not([fill='none']) {
        fill: currentColor;
      }
      :host-context(.sbb-icon-inherit-color) [stroke]:not([stroke='none']) {
        stroke: currentColor;
      }
    `
  ],
  host: {
    xmlns: 'http://www.w3.org/2000/svg',
    viewBox: '0 0 24 24',
    class: 'sbb-icon sbb-icon-kom sbb-icon-weather',
    focusable: 'false'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SvgIconCloudDenseFogSmall {}

@Component({
  selector: 'sbb-icon-cloud-dense-fog-small',
  template: `
    <svg sbbIconCloudDenseFogSmall></svg>
  `,
  host: {
    class: 'sbb-icon-wrapper'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconCloudDenseFogSmall {}

@NgModule({
  declarations: [SvgIconCloudDenseFogSmall, IconCloudDenseFogSmall],
  exports: [SvgIconCloudDenseFogSmall, IconCloudDenseFogSmall]
})
export class IconCloudDenseFogSmallModule {}
