/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

@Component({
  selector: 'svg[sbbIconSaVc]',
  template: `
    <svg:g fill="#000" fill-rule="evenodd">
      <svg:path
        d="M3.14 1.038h2.8L7.243 11.9h.04l5.8-10.862h3.042L8.322 15H4.98zM27.123 3.818c-.64-.44-1.7-.82-3.2-.82-3.102 0-5.281 2.34-5.281 5.62 0 2.34 1.519 4.422 3.98 4.422 1.181 0 2.141-.38 2.94-.86l-.439 2.68c-1.021.28-2.101.38-3.161.38-4.221 0-6.241-2.84-6.241-6.621 0-4.501 3.06-7.822 8.002-7.822 1.4 0 2.879.18 4.1.68l-.7 2.34z"
      />
    </svg:g>
  `,
  styles: [
    `
      :host-context(.sbb-icon-fixed-size) {
        width: 29px;
        height: 16px;
      }
      :host-context(.sbb-icon-inherit-color) [fill]:not([fill='none']) {
        fill: currentColor;
      }
      :host-context(.sbb-icon-inherit-color) [stroke]:not([stroke='none']) {
        stroke: currentColor;
      }
    `
  ],
  host: {
    xmlns: 'http://www.w3.org/2000/svg',
    viewBox: '0 0 29 16',
    class: 'sbb-icon sbb-icon-fpl sbb-icon-timetable-attributes',
    focusable: 'false'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SvgIconSaVc {}

@Component({
  selector: 'sbb-icon-sa-vc',
  template: `
    <svg sbbIconSaVc></svg>
  `,
  host: {
    class: 'sbb-icon-wrapper'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconSaVc {}

@NgModule({
  declarations: [SvgIconSaVc, IconSaVc],
  exports: [SvgIconSaVc, IconSaVc]
})
export class IconSaVcModule {}
