/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

@Component({
  selector: 'svg[sbbIconMugHotMedium]',
  template: `
    <svg:path
      fill="none"
      stroke="#000"
      d="M23.25 27.75h4.5v-9h-4.5v9zM11.25 3c0 .9.9 2.25 2.25 2.25 2.7 0 3.15 4.5 0 4.5-1.2 0-2.25.9-2.25 2.25m6-9c0 .9.9 2.25 2.25 2.25 2.7 0 3.15 4.5 0 4.5-1.2 0-2.25.9-2.25 2.25m-9 18.75h15v-16.5h-15v16.5z"
    />
  `,
  styles: [
    `
      :host-context(.sbb-icon-fixed-size) {
        width: 36px;
        height: 36px;
      }
      :host-context(.sbb-icon-inherit-color) [fill]:not([fill='none']) {
        fill: currentColor;
      }
      :host-context(.sbb-icon-inherit-color) [stroke]:not([stroke='none']) {
        stroke: currentColor;
      }
    `
  ],
  host: {
    xmlns: 'http://www.w3.org/2000/svg',
    viewBox: '0 0 36 36',
    class: 'sbb-icon sbb-icon-kom sbb-icon-basic',
    focusable: 'false'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SvgIconMugHotMedium {}

@Component({
  selector: 'sbb-icon-mug-hot-medium',
  template: `
    <svg sbbIconMugHotMedium></svg>
  `,
  host: {
    class: 'sbb-icon-wrapper'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconMugHotMedium {}

@NgModule({
  declarations: [SvgIconMugHotMedium, IconMugHotMedium],
  exports: [SvgIconMugHotMedium, IconMugHotMedium]
})
export class IconMugHotMediumModule {}
