/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

@Component({
  selector: 'svg[sbbIconHourglassSmall]',
  template: `
    <svg:path
      fill="none"
      stroke="#000"
      d="M18.516 20.5c0-2.82-1.926-5.266-3.979-6.504-.624-.384-1.053-1.135-1.053-1.996s.43-1.612 1.053-1.995c2.053-1.238 3.98-3.686 3.98-6.505H5.483c0 2.819 1.925 5.267 3.978 6.505.624.383 1.054 1.134 1.054 1.995 0 .86-.43 1.612-1.054 1.996C7.41 15.234 5.484 17.68 5.484 20.5h13.032zm-9.052-13c.33.307.683.577 1.04.793l.003.002c.656.404 1.155 1.091 1.492 1.836.336-.743.832-1.429 1.485-1.83a6.594 6.594 0 001.052-.8H9.464z"
    />
  `,
  styles: [
    `
      :host-context(.sbb-icon-fixed-size) {
        width: 24px;
        height: 24px;
      }
      :host-context(.sbb-icon-inherit-color) [fill]:not([fill='none']) {
        fill: currentColor;
      }
      :host-context(.sbb-icon-inherit-color) [stroke]:not([stroke='none']) {
        stroke: currentColor;
      }
    `
  ],
  host: {
    xmlns: 'http://www.w3.org/2000/svg',
    viewBox: '0 0 24 24',
    class: 'sbb-icon sbb-icon-kom sbb-icon-timetable',
    focusable: 'false'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SvgIconHourglassSmall {}

@Component({
  selector: 'sbb-icon-hourglass-small',
  template: `
    <svg sbbIconHourglassSmall></svg>
  `,
  host: {
    class: 'sbb-icon-wrapper'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconHourglassSmall {}

@NgModule({
  declarations: [SvgIconHourglassSmall, IconHourglassSmall],
  exports: [SvgIconHourglassSmall, IconHourglassSmall]
})
export class IconHourglassSmallModule {}
