/*
 * Don't delete this file, it's autogenerated by the ACL icons build script
 */
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

import { IconBase } from '../../icon-base';

@Component({
  selector: 'sbb-icon-wallbox-48',
  // tslint:disable-next-line:max-line-length
  template: `<svg [attr.class]="'sbb-svg-icon ' + svgClass" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48"><path d="M41 35V23.284l-9-8.47-.198.186h-16L7 23.284V35H4v1h40v-1zm-1-11.284V35H24V23.716l8-7.53zM16.198 16H30.74l-7.437 7H8.76zM8 24h15v11h-6v-6h-6v6H8zm8 11h-4v-5h4z"/><path d="M32.565 28l-2.481 3.723.832.554L34.435 27h-3l2.481-3.723-.832-.554L29.565 28h3z"/></svg>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class IconWallbox48Component extends IconBase {
  constructor() {
    super({ width: '48px', height: '48px', ratio: 1 });
  }
}

@NgModule({
  declarations: [IconWallbox48Component],
  exports: [IconWallbox48Component],
})
export class IconWallbox48Module { }
