/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

@Component({
  selector: 'svg[<%= prefix %>Icon<%= classify(normalizedName) %>]',
  template: `<%= template %>`,
  styles: [`
    :host-context(.sbb-icon-fixed-size) {
      width: <%= width %>;
      height: <%= height %>;
    }
    :host-context(.sbb-icon-inherit-color) [fill]:not([fill="none"]) {
      fill: currentColor;
    }
    :host-context(.sbb-icon-inherit-color) [stroke]:not([stroke="none"]) {
      stroke: currentColor;
    }
  `],
  host: {<% for (let attr of attributes) { %>
    '<%= attr.key %>': '<%= attr.value %>',<% } %>
    'class': '<%= prefix %>-icon <%= cssClasses %>',
    'focusable': 'false'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SvgIcon<%= classify(normalizedName) %> {}

@Component({
  selector: 'sbb-icon-<%= dasherize(normalizedName) %>',
  template: `<svg <%= prefix %>Icon<%= classify(normalizedName) %>></svg>`,
  host: {
    'class': 'sbb-icon-wrapper'
  },
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Icon<%= classify(normalizedName) %> {}

@NgModule({
  declarations: [SvgIcon<%= classify(normalizedName) %>, Icon<%= classify(normalizedName) %>],
  exports: [SvgIcon<%= classify(normalizedName) %>, Icon<%= classify(normalizedName) %>],
})
export class Icon<%= classify(normalizedName) %>Module { }
