/*
 * Autogenerated by schematics
 */
import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

import { IconBase } from '../icon-base';

@Component({
  selector: 'sbb-icon-lotus',
  // tslint:disable:max-line-length
  template: `<svg [attr.class]="'sbb-svg-icon ' + svgClass" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 36 36"><path fill="none" stroke="#000" d="M12.75 14.625c0 3.909 1.935 7.602 5.25 10.014 5.956-4.335 7-12.333 2.331-17.863A13.217 13.217 0 0 0 18 4.61c-3.315 2.41-5.25 6.105-5.25 10.014zm-8.404 4.838a12.965 12.965 0 0 0-2.365 1.674A12.712 12.712 0 0 0 15 27.74m6 0a12.71 12.71 0 0 0 13.019-6.603 12.914 12.914 0 0 0-2.364-1.674m-21.16-8.654a12.673 12.673 0 0 0-4.966-.855c-1.443 6.8 2.853 13.497 9.638 15.017m10.337-14.162a12.673 12.673 0 0 1 4.967-.855c1.443 6.8-2.853 13.497-9.638 15.017"/></svg>`,
  // tslint:enable:max-line-length
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class IconLotusComponent extends IconBase {
  constructor() {
    super({ width: '24px', height: '24px', ratio: 1 });
  }
}

@NgModule({
  imports: [CommonModule],
  declarations: [IconLotusComponent],
  exports: [IconLotusComponent],
})
export class IconLotusModule { }
