/*
 * Autogenerated by schematics
 */
import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

import { IconBase } from '../icon-base';

@Component({
  selector: 'sbb-icon-station',
  // tslint:disable:max-line-length
  template: `<svg [attr.class]="'sbb-svg-icon ' + svgClass" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 36 36"><path fill="none" stroke="#000" d="M15.9 13.95l2.85 2.55 2.85-3.6m3.15 2.85c0 3.348-2.652 6-6 6s-6-2.652-6-6 2.652-6 6-6 6 2.652 6 6zm-19.5-7.8v22.8h7.5v-4.486h12v4.486h7.5V7.95c-8.958-3.655-17.956-3.593-27 0z"/></svg>`,
  // tslint:enable:max-line-length
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class IconStationComponent extends IconBase {
  constructor() {
    super({ width: '24px', height: '24px', ratio: 1 });
  }
}

@NgModule({
  imports: [CommonModule],
  declarations: [IconStationComponent],
  exports: [IconStationComponent],
})
export class IconStationModule { }
