/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

@Component({
  selector: 'svg[sbbIconWaitingRoomMedium]',
  template: `
    <svg:path
      fill="none"
      stroke="#000"
      d="M21.9 9.45L24.75 12l2.85-3.6m3.15 2.85c0 3.348-2.652 6-6 6-3.346 0-6-2.652-6-6s2.654-6 6-6c3.348 0 6 2.652 6 6zm-12 19.5h12v-7.485h-12v7.485zm3.752-8.986h4.5M9.748 9.75a1.5 1.5 0 11-3 0 1.5 1.5 0 013 0zm1.5 12v-7.5h-6v7.5h1.5v9h3v-9h1.5z"
    />
  `,
  styles: [
    `
      :host-context(.sbb-icon-fixed-size) {
        width: 36px;
        height: 36px;
      }
      :host-context(.sbb-icon-inherit-color) [fill]:not([fill='none']) {
        fill: currentColor;
      }
      :host-context(.sbb-icon-inherit-color) [stroke]:not([stroke='none']) {
        stroke: currentColor;
      }
    `
  ],
  host: {
    xmlns: 'http://www.w3.org/2000/svg',
    viewBox: '0 0 36 36',
    class: 'sbb-icon sbb-icon-kom sbb-icon-station',
    focusable: 'false'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SvgIconWaitingRoomMedium {}

@Component({
  selector: 'sbb-icon-waiting-room-medium',
  template: `
    <svg sbbIconWaitingRoomMedium></svg>
  `,
  host: {
    class: 'sbb-icon-wrapper'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconWaitingRoomMedium {}

@NgModule({
  declarations: [SvgIconWaitingRoomMedium, IconWaitingRoomMedium],
  exports: [SvgIconWaitingRoomMedium, IconWaitingRoomMedium]
})
export class IconWaitingRoomMediumModule {}
