
/*
* Don't delete this file, it's autogenerated by the ACL icons build script
*/
import { Component, Input } from '@angular/core';
@Component({
  selector: 'sbb-icon-download',
  // tslint:disable-next-line:max-line-length
  template: '<svg [ngClass]="[svgClass, commonClass]" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M15.8 11.7l-.7-.7-3.1 3.1V7h-1v7.1L7.9 11l-.7.7 4.2 4.3 4.4-4.3zM18 15v2H5v-2H4v3h15v-3h-1z"/></svg>',
  styles: []
})
export class IconDownloadComponent {

  @Input() svgClass = '';
  commonClass = ' ';
}
