/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable

export * from './twitter';
export * from './facebook';
export * from './instagram';
export * from './youtube';
export * from './linkedin';
export * from './pinterest';
export * from './xing';
