/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

@Component({
  selector: 'svg[sbbIconPauseSmall]',
  template: `
    <svg:path fill="none" stroke="#000" d="M13.501 18.5v-13h3v13h-3zm-6.001 0v-13h3v13h-3z" />
  `,
  styles: [
    `
      :host-context(.sbb-icon-fixed-size) {
        width: 24px;
        height: 24px;
      }
      :host-context(.sbb-icon-inherit-color) [fill]:not([fill='none']) {
        fill: currentColor;
      }
      :host-context(.sbb-icon-inherit-color) [stroke]:not([stroke='none']) {
        stroke: currentColor;
      }
    `
  ],
  host: {
    xmlns: 'http://www.w3.org/2000/svg',
    viewBox: '0 0 24 24',
    class: 'sbb-icon sbb-icon-kom sbb-icon-audio',
    focusable: 'false'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SvgIconPauseSmall {}

@Component({
  selector: 'sbb-icon-pause-small',
  template: `
    <svg sbbIconPauseSmall></svg>
  `,
  host: {
    class: 'sbb-icon-wrapper'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconPauseSmall {}

@NgModule({
  declarations: [SvgIconPauseSmall, IconPauseSmall],
  exports: [SvgIconPauseSmall, IconPauseSmall]
})
export class IconPauseSmallModule {}
