/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable

export * from './fast-forward-medium';
export * from './next-medium';
export * from './pause-medium';
export * from './play-medium';
export * from './previous-medium';
export * from './record-medium';
export * from './rewind-medium';
export * from './stop-medium';
export * from './fast-forward-small';
export * from './next-small';
export * from './pause-small';
export * from './play-small';
export * from './previous-small';
export * from './record-small';
export * from './rewind-small';
export * from './stop-small';
