
/*
* Don't delete this file, it's autogenerated by the ACL icons build script
*/
import { NgModule } from '@angular/core';
import { IconCollectionBaseDocumentsModule } from '../../../svg-icons/svg-icons';

/**
 * @deprecated Use IconCollectionBaseDocumentsModule
 */
@NgModule({
  imports: [IconCollectionBaseDocumentsModule],
  exports: [IconCollectionBaseDocumentsModule],
})
export class IconDocumentsModule { }
