/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

@Component({
  selector: 'svg[sbbIconLiftSmall]',
  template: `
    <svg:path
      fill="none"
      stroke="#000"
      d="M2.75 20.25h11.5V3.75H2.75v16.5zM16.879 6l2.12-2.122L21.122 6m0 12l-2.12 2.122L16.878 18M9.5 6.5a1 1 0 11-2-.002 1 1 0 012 .001zm1 7.999v-5h-4v5h1v4h2v-4h1z"
    />
  `,
  styles: [
    `
      :host-context(.sbb-icon-fixed-size) {
        width: 24px;
        height: 24px;
      }
      :host-context(.sbb-icon-inherit-color) [fill]:not([fill='none']) {
        fill: currentColor;
      }
      :host-context(.sbb-icon-inherit-color) [stroke]:not([stroke='none']) {
        stroke: currentColor;
      }
    `
  ],
  host: {
    xmlns: 'http://www.w3.org/2000/svg',
    viewBox: '0 0 24 24',
    class: 'sbb-icon sbb-icon-kom sbb-icon-station',
    focusable: 'false'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SvgIconLiftSmall {}

@Component({
  selector: 'sbb-icon-lift-small',
  template: `
    <svg sbbIconLiftSmall></svg>
  `,
  host: {
    class: 'sbb-icon-wrapper'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconLiftSmall {}

@NgModule({
  declarations: [SvgIconLiftSmall, IconLiftSmall],
  exports: [SvgIconLiftSmall, IconLiftSmall]
})
export class IconLiftSmallModule {}
