/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

@Component({
  selector: 'svg[sbbIconPlatformDisplayMedium]',
  template: `
    <svg:path
      fill="none"
      stroke="#000"
      d="M29.252 14.25V12M6.748 14.25V12M3.75 23.25h28.5v-9H3.75v9zm2.25-6h3m1.5 0H30m-19.5 3.001H30"
    />
  `,
  styles: [
    `
      :host-context(.sbb-icon-fixed-size) {
        width: 36px;
        height: 36px;
      }
      :host-context(.sbb-icon-inherit-color) [fill]:not([fill='none']) {
        fill: currentColor;
      }
      :host-context(.sbb-icon-inherit-color) [stroke]:not([stroke='none']) {
        stroke: currentColor;
      }
    `
  ],
  host: {
    xmlns: 'http://www.w3.org/2000/svg',
    viewBox: '0 0 36 36',
    class: 'sbb-icon sbb-icon-kom sbb-icon-station',
    focusable: 'false'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SvgIconPlatformDisplayMedium {}

@Component({
  selector: 'sbb-icon-platform-display-medium',
  template: `
    <svg sbbIconPlatformDisplayMedium></svg>
  `,
  host: {
    class: 'sbb-icon-wrapper'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconPlatformDisplayMedium {}

@NgModule({
  declarations: [SvgIconPlatformDisplayMedium, IconPlatformDisplayMedium],
  exports: [SvgIconPlatformDisplayMedium, IconPlatformDisplayMedium]
})
export class IconPlatformDisplayMediumModule {}
