/*
 * Autogenerated by schematics
 */
export * from './icon-arrows-circle.module';
export * from './icon-arrows-left-right.module';
export * from './icon-arrows-left-right-down-up.module';
export * from './icon-arrows-right-left.module';
export * from './icon-arrows-up-down.module';
export * from './icon-arrow-circle.module';
export * from './icon-arrow-long-left.module';
export * from './icon-arrow-long-right.module';
export * from './icon-arrow-right.module';
export * from './icon-chevron-right.module';
export * from './icon-chevron-small-down.module';
export * from './icon-chevron-small-down-circle.module';
export * from './icon-chevron-small-left.module';
export * from './icon-chevron-small-left-circle.module';
export * from './icon-chevron-small-right.module';
export * from './icon-chevron-small-right-circle.module';
export * from './icon-chevron-small-up.module';
export * from './icon-chevron-small-up-circle.module';
export * from './icon-increase-size.module';
export * from './icon-reduce-size.module';
export * from './icon-collection-arrow.module';
