/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

@Component({
  selector: 'svg[sbbIconSpeechBubbleSmall]',
  template: `
    <svg:path
      fill="none"
      stroke="#000"
      d="M4.5 6.5h15v11H9.75L7.5 19.75V17.5h-3v-11zM7 9.479h10.021M6.979 11.563H17m-10.021 2h7.979"
    />
  `,
  styles: [
    `
      :host-context(.sbb-icon-fixed-size) {
        width: 24px;
        height: 24px;
      }
      :host-context(.sbb-icon-inherit-color) [fill]:not([fill='none']) {
        fill: currentColor;
      }
      :host-context(.sbb-icon-inherit-color) [stroke]:not([stroke='none']) {
        stroke: currentColor;
      }
    `
  ],
  host: {
    xmlns: 'http://www.w3.org/2000/svg',
    viewBox: '0 0 24 24',
    class: 'sbb-icon sbb-icon-kom sbb-icon-community',
    focusable: 'false'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SvgIconSpeechBubbleSmall {}

@Component({
  selector: 'sbb-icon-speech-bubble-small',
  template: `
    <svg sbbIconSpeechBubbleSmall></svg>
  `,
  host: {
    class: 'sbb-icon-wrapper'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconSpeechBubbleSmall {}

@NgModule({
  declarations: [SvgIconSpeechBubbleSmall, IconSpeechBubbleSmall],
  exports: [SvgIconSpeechBubbleSmall, IconSpeechBubbleSmall]
})
export class IconSpeechBubbleSmallModule {}
