/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

@Component({
  selector: 'svg[sbbIconSpeechBubbleGroupEmptyMedium]',
  template: `
    <svg:path
      fill="none"
      stroke="#000"
      d="M5.25 6.75h12v7.5h-7.125L6.75 17.625V14.25h-1.5v-7.5zm19.5 12v9h-3v3.375l-3.375-3.375H11.25v-9h13.5zm6-10.5v6h-1.5v3.375l-3.375-3.375H21.75v-6h9z"
    />
  `,
  styles: [
    `
      :host-context(.sbb-icon-fixed-size) {
        width: 36px;
        height: 36px;
      }
      :host-context(.sbb-icon-inherit-color) [fill]:not([fill='none']) {
        fill: currentColor;
      }
      :host-context(.sbb-icon-inherit-color) [stroke]:not([stroke='none']) {
        stroke: currentColor;
      }
    `
  ],
  host: {
    xmlns: 'http://www.w3.org/2000/svg',
    viewBox: '0 0 36 36',
    class: 'sbb-icon sbb-icon-kom sbb-icon-community',
    focusable: 'false'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SvgIconSpeechBubbleGroupEmptyMedium {}

@Component({
  selector: 'sbb-icon-speech-bubble-group-empty-medium',
  template: `
    <svg sbbIconSpeechBubbleGroupEmptyMedium></svg>
  `,
  host: {
    class: 'sbb-icon-wrapper'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconSpeechBubbleGroupEmptyMedium {}

@NgModule({
  declarations: [SvgIconSpeechBubbleGroupEmptyMedium, IconSpeechBubbleGroupEmptyMedium],
  exports: [SvgIconSpeechBubbleGroupEmptyMedium, IconSpeechBubbleGroupEmptyMedium]
})
export class IconSpeechBubbleGroupEmptyMediumModule {}
