
/*
* Don't delete this file, it's autogenerated by the ACL icons build script
*/
import { Component, Input } from '@angular/core';
@Component({
  selector: 'sbb-icon-service-sn',
  // tslint:disable-next-line:max-line-length
  template: '<svg [attr.class]="svgClass + commonClass" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 23 13"><path d="M2.1 12.3c-.3-.5-.6-.9-.8-1.3-.2-.4-.5-.9-.8-1.7C.2 8.6 0 7.6 0 6.5c0-1.1.2-2 .5-2.9.4-.8.9-1.8 1.6-2.9h1.2c-.4.7-.7 1.2-.9 1.6-.2.4-.4 1-.7 1.7-.3.8-.4 1.6-.4 2.5 0 1 .2 1.8.5 2.6s.5 1.3.7 1.7c.2.3.5.8.8 1.5H2.1zm6.3-4.1l-1.8-2-.8-1c-.4-.6-.6-1.2-.6-2 0-1 .4-2 1.1-2.9l.2-.2.1-.1 4.5 5.1V3.2L14.6 0l.8.9-3.1 2.8v1.5l3.8-3.5.9.9-3.8 3.5 1.5.1 3.1-2.8.8.9-3.5 3.2-2-.1 3.8 4.3-1.6 1.3-4-4.5-.1-.3-.1.3L6.2 13l-1.4-1.5 3.6-3.3zM6.7 2.3c-.1.1-.1.3-.1.4v.4c0 .6.2 1.2.7 1.7l.5.5 1.7 1.9 1-.9-3.7-4-.1-.3v.3zM20.5.7c.6 1 1.2 1.9 1.6 2.8.4.9.6 1.9.6 3 0 .5-.1 1.1-.2 1.6s-.3 1-.5 1.5-.4.9-.6 1.2c-.2.3-.5.8-.9 1.5h-1.2c.4-.7.7-1.2.9-1.6.2-.4.4-1 .7-1.7.3-.7.4-1.6.4-2.5 0-1-.1-1.8-.4-2.6s-.5-1.3-.7-1.7c-.2-.4-.5-.9-.9-1.5h1.2z"/></svg>',
  styles: []
})
export class IconServiceSnComponent {

  @Input() svgClass = '';
  commonClass = ' ';
}
