
/*
* Don't delete this file, it's autogenerated by the ACL icons build script
*/
import { NgModule } from '@angular/core';
import { IconCollectionProductsModule } from '../../svg-icons/svg-icons';

/**
 * @deprecated Use IconCollectionProductsModule
 */
@NgModule({
  imports: [IconCollectionProductsModule],
  exports: [IconCollectionProductsModule],
})
export class IconProductsModule { }
