
/*
* Don't delete this file, it's autogenerated by the ACL icons build script
*/
import { NgModule } from '@angular/core';
import { IconCollectionWebshopUtilizationModule } from '../../../svg-icons/svg-icons';

/**
 * @deprecated Use IconCollectionWebshopUtilizationModule
 */
@NgModule({
  imports: [IconCollectionWebshopUtilizationModule],
  exports: [IconCollectionWebshopUtilizationModule],
})
export class IconUtilizationModule { }
