/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

@Component({
  selector: 'svg[sbbIconThumbUpSmall]',
  template: `
    <svg:path
      fill="none"
      stroke="#000"
      d="M16 12.5h1.5M5.499 18.51H8.5v-8.008H5.499v8.008zM16 14.499h1.5M16 16.502h.5m1-6a1 1 0 110 2 1 1 0 110 2 1 1 0 110 2h-1a1 1 0 010 2h-5c-1.508 0-3-.5-3-3v-5h1l4.29-4.706a1.002 1.002 0 011.648 1.052L14 10.5h3.5"
    />
  `,
  styles: [
    `
      :host-context(.sbb-icon-fixed-size) {
        width: 24px;
        height: 24px;
      }
      :host-context(.sbb-icon-inherit-color) [fill]:not([fill='none']) {
        fill: currentColor;
      }
      :host-context(.sbb-icon-inherit-color) [stroke]:not([stroke='none']) {
        stroke: currentColor;
      }
    `
  ],
  host: {
    xmlns: 'http://www.w3.org/2000/svg',
    viewBox: '0 0 24 24',
    class: 'sbb-icon sbb-icon-kom sbb-icon-community',
    focusable: 'false'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SvgIconThumbUpSmall {}

@Component({
  selector: 'sbb-icon-thumb-up-small',
  template: `
    <svg sbbIconThumbUpSmall></svg>
  `,
  host: {
    class: 'sbb-icon-wrapper'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconThumbUpSmall {}

@NgModule({
  declarations: [SvgIconThumbUpSmall, IconThumbUpSmall],
  exports: [SvgIconThumbUpSmall, IconThumbUpSmall]
})
export class IconThumbUpSmallModule {}
