/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

@Component({
  selector: 'svg[sbbIconLocationPinMedium]',
  template: `
    <svg:path
      fill="none"
      stroke="#000"
      d="M23.238 13.51a5.25 5.25 0 11-10.5 0 5.25 5.25 0 0110.5 0zm2.989.012a8.25 8.25 0 00-16.5 0c.055 1.414.474 2.604 1.149 3.729L18 28.498l7.125-11.247c.664-1.166 1.089-2.378 1.1-3.73z"
    />
  `,
  styles: [
    `
      :host-context(.sbb-icon-fixed-size) {
        width: 36px;
        height: 36px;
      }
      :host-context(.sbb-icon-inherit-color) [fill]:not([fill='none']) {
        fill: currentColor;
      }
      :host-context(.sbb-icon-inherit-color) [stroke]:not([stroke='none']) {
        stroke: currentColor;
      }
    `
  ],
  host: {
    xmlns: 'http://www.w3.org/2000/svg',
    viewBox: '0 0 36 36',
    class: 'sbb-icon sbb-icon-kom sbb-icon-location',
    focusable: 'false'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SvgIconLocationPinMedium {}

@Component({
  selector: 'sbb-icon-location-pin-medium',
  template: `
    <svg sbbIconLocationPinMedium></svg>
  `,
  host: {
    class: 'sbb-icon-wrapper'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconLocationPinMedium {}

@NgModule({
  declarations: [SvgIconLocationPinMedium, IconLocationPinMedium],
  exports: [SvgIconLocationPinMedium, IconLocationPinMedium]
})
export class IconLocationPinMediumModule {}
