/*
 * Don't delete this file, it's autogenerated by the ACL icons build script
 */
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

import { IconBase } from '../icon-base';

/** @deprecated Use `sbb-angular-icons` instead. */
@Component({
  selector: 'sbb-icon-product-vae',
  // tslint:disable-next-line
  template: `<svg [attr.class]="'sbb-svg-icon ' + svgClass" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 59 20"><path d="M14.695 4.2h-2.632l-2.615 8.156h-.033L6.832 4.2H4.2l3.77 11.6h2.875l3.85-11.6zm-1.107 11.6h2.583l.91-2.583h4.338l.877 2.583h2.648L20.607 4.2H17.99l-4.403 11.6zm5.67-8.74h.033l1.462 4.256h-3.006l1.511-4.257zm6.578 8.74h8.805v-2.145h-6.255v-2.843h5.622V8.83h-5.622V6.345h6.125V4.2h-8.675v11.6z"/></svg>`,
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconProductVaeComponent extends IconBase {
  constructor() {
    super({ width: '59px', height: '20px', ratio: 2.95 });
  }
}

/** @deprecated Use `sbb-angular-icons` instead. */
@NgModule({
  declarations: [IconProductVaeComponent],
  exports: [IconProductVaeComponent]
})
export class IconProductVaeModule {}
