/*
 * Don't delete this file, it's autogenerated by the ACL icons build script
 */
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

import { IconBase } from '../icon-base';

@Component({
  selector: 'sbb-icon-product-nj',
  // tslint:disable-next-line:max-line-length
  template: `<svg [attr.class]="'sbb-svg-icon ' + svgClass" [attr.viewBox]="viewBox" [attr.preserveAspectRatio]="preserveAspectRatio" [attr.width]="width" [attr.height]="height" xmlns="http://www.w3.org/2000/svg"><text font-size="16.038" transform="translate(3.285 15.591)">NJ</text></svg>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class IconProductNjComponent extends IconBase {
  constructor() {
    super({ viewBox: '0 0 59 20' });
  }
}

@NgModule({
  declarations: [IconProductNjComponent],
  exports: [IconProductNjComponent],
})
export class IconProductNjModule { }
