/*
 * Don't delete this file, it's autogenerated by the ACL icons build script
 */
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

import { IconBase } from '../icon-base';

@Component({
  selector: 'sbb-icon-product-ic-2',
  // tslint:disable-next-line:max-line-length
  template: `<svg [attr.class]="'sbb-svg-icon ' + svgClass" [attr.viewBox]="viewBox" [attr.preserveAspectRatio]="preserveAspectRatio" [attr.width]="width" [attr.height]="height" xmlns="http://www.w3.org/2000/svg"><path d="M223.9 70.1v10.3h-41.6c0-3.1.5-6.1 1.5-9 .9-2.7 2.4-5.2 4.3-7.4 1.5-1.7 3.2-3.2 5-4.6 1.9-1.5 5.7-4.3 11.4-8.3 2.2-1.4 4.2-3.3 5.8-5.4 1.1-1.7 1.7-3.7 1.7-5.8.1-2.3-.7-4.5-2.2-6.2-1.5-1.6-3.7-2.4-5.9-2.4-6 0-9 4.3-9.2 12.9h-11.1v-1.3c0-7 2-12.4 5.9-16.3 3.8-3.7 8.8-5.6 14.8-5.6 4.9-.2 9.7 1.5 13.5 4.6 3.9 3.3 5.9 7.8 5.9 13.4.1 4.7-1.6 9.2-4.7 12.7-.9 1-1.8 1.9-2.9 2.8-.9.7-3.3 2.4-7.1 5-3.6 2.5-6.2 4.5-7.8 5.8-1.6 1.4-3.1 2.9-4.4 4.6l27.1.2zM46.3 21h20.3L41.4 79H21l25.3-58zM80 21h72.2l-7.5 17.2H93.2L82.9 61.8h51.6L127.1 79H54.8L80 21z"/></svg>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class IconProductIc2Component extends IconBase {
  constructor() {
    super({ viewBox: '0 0 296 100' });
  }
}

@NgModule({
  declarations: [IconProductIc2Component],
  exports: [IconProductIc2Component],
})
export class IconProductIc2Module { }
