/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

@Component({
  selector: 'svg[sbbIconAppIconSmall]',
  template: `
    <svg:g fill="none" fill-rule="evenodd">
      <svg:path
        fill="#000"
        d="M13.475 9l2.744 2.704h-3.412V9h-1.613v2.704H7.801L10.545 9h-2.04L5 12.5 8.505 16h2.04l-2.744-2.686h3.393V16h1.613v-2.686h3.412L13.475 16h2.039L19 12.5 15.514 9z"
      />
      <svg:path
        stroke="#000"
        d="M2.5 6.36A3.86 3.86 0 016.359 2.5h11.282A3.86 3.86 0 0121.5 6.36v11.28a3.86 3.86 0 01-3.859 3.86H6.359A3.86 3.86 0 012.5 17.64V6.36z"
      />
    </svg:g>
  `,
  styles: [
    `
      :host-context(.sbb-icon-fixed-size) {
        width: 24px;
        height: 24px;
      }
      :host-context(.sbb-icon-inherit-color) [fill]:not([fill='none']) {
        fill: currentColor;
      }
      :host-context(.sbb-icon-inherit-color) [stroke]:not([stroke='none']) {
        stroke: currentColor;
      }
    `
  ],
  host: {
    xmlns: 'http://www.w3.org/2000/svg',
    viewBox: '0 0 24 24',
    class: 'sbb-icon sbb-icon-kom sbb-icon-basic',
    focusable: 'false'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SvgIconAppIconSmall {}

@Component({
  selector: 'sbb-icon-app-icon-small',
  template: `
    <svg sbbIconAppIconSmall></svg>
  `,
  host: {
    class: 'sbb-icon-wrapper'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconAppIconSmall {}

@NgModule({
  declarations: [SvgIconAppIconSmall, IconAppIconSmall],
  exports: [SvgIconAppIconSmall, IconAppIconSmall]
})
export class IconAppIconSmallModule {}
