/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

@Component({
  selector: 'svg[sbbIconCircleInformationSmallSmall]',
  template: `
    <svg:path
      fill="none"
      stroke="#000"
      d="M19.5 12c0 4.188-3.313 7.5-7.5 7.5-4.188 0-7.5-3.312-7.5-7.5 0-4.188 3.312-7.5 7.5-7.5 4.187 0 7.5 3.312 7.5 7.5zm-7.02-3V7m2.5 8.49h-5m2.5 0v-5H10"
    />
  `,
  styles: [
    `
      :host-context(.sbb-icon-fixed-size) {
        width: 24px;
        height: 24px;
      }
      :host-context(.sbb-icon-inherit-color) [fill]:not([fill='none']) {
        fill: currentColor;
      }
      :host-context(.sbb-icon-inherit-color) [stroke]:not([stroke='none']) {
        stroke: currentColor;
      }
    `
  ],
  host: {
    xmlns: 'http://www.w3.org/2000/svg',
    viewBox: '0 0 24 24',
    class: 'sbb-icon sbb-icon-kom sbb-icon-basic',
    focusable: 'false'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SvgIconCircleInformationSmallSmall {}

@Component({
  selector: 'sbb-icon-circle-information-small-small',
  template: `
    <svg sbbIconCircleInformationSmallSmall></svg>
  `,
  host: {
    class: 'sbb-icon-wrapper'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconCircleInformationSmallSmall {}

@NgModule({
  declarations: [SvgIconCircleInformationSmallSmall, IconCircleInformationSmallSmall],
  exports: [SvgIconCircleInformationSmallSmall, IconCircleInformationSmallSmall]
})
export class IconCircleInformationSmallSmallModule {}
