/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

@Component({
  selector: 'svg[sbbIconTreeSmall]',
  template: `
    <svg:path
      fill="none"
      stroke="#000"
      d="M2 21.5h20H2zm9.5 0V9v12.5zm0-5.5l3.5-4-3.5 4zm0-3L9 11l2.5 2zm8.508-1.852c.31-.472.492-1.034.492-1.64a3 3 0 00-3-3c-.382 0-.744.078-1.08.209-.381-2.383-2.43-4.21-4.92-4.21a5 5 0 00-5 5c0 .358.04.704.112 1.04-2.301.2-4.112 2.109-4.112 4.46a4.5 4.5 0 004.5 4.5h11a3.5 3.5 0 003.5-3.5 3.491 3.491 0 00-1.492-2.86z"
    />
  `,
  styles: [
    `
      :host-context(.sbb-icon-fixed-size) {
        width: 24px;
        height: 24px;
      }
      :host-context(.sbb-icon-inherit-color) [fill]:not([fill='none']) {
        fill: currentColor;
      }
      :host-context(.sbb-icon-inherit-color) [stroke]:not([stroke='none']) {
        stroke: currentColor;
      }
    `
  ],
  host: {
    xmlns: 'http://www.w3.org/2000/svg',
    viewBox: '0 0 24 24',
    class: 'sbb-icon sbb-icon-kom sbb-icon-basic',
    focusable: 'false'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SvgIconTreeSmall {}

@Component({
  selector: 'sbb-icon-tree-small',
  template: `
    <svg sbbIconTreeSmall></svg>
  `,
  host: {
    class: 'sbb-icon-wrapper'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconTreeSmall {}

@NgModule({
  declarations: [SvgIconTreeSmall, IconTreeSmall],
  exports: [SvgIconTreeSmall, IconTreeSmall]
})
export class IconTreeSmallModule {}
