/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

@Component({
  selector: 'svg[sbbIconSaLe]',
  template: `
    <svg:g fill="#000" fill-rule="evenodd">
      <svg:path
        d="M4.42 1.037h2.802L4.72 12.8h5.48l-.48 2.2H1.46zM14.56 1.037h8.222l-.42 2.2h-5.46l-.722 3.441h4.883l-.44 2.201H15.72L14.9 12.8h5.522l-.48 2.2H11.62z"
      />
    </svg:g>
  `,
  styles: [
    `
      :host-context(.sbb-icon-fixed-size) {
        width: 24px;
        height: 16px;
      }
      :host-context(.sbb-icon-inherit-color) [fill]:not([fill='none']) {
        fill: currentColor;
      }
      :host-context(.sbb-icon-inherit-color) [stroke]:not([stroke='none']) {
        stroke: currentColor;
      }
    `
  ],
  host: {
    xmlns: 'http://www.w3.org/2000/svg',
    viewBox: '0 0 24 16',
    class: 'sbb-icon sbb-icon-fpl sbb-icon-timetable-attributes',
    focusable: 'false'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SvgIconSaLe {}

@Component({
  selector: 'sbb-icon-sa-le',
  template: `
    <svg sbbIconSaLe></svg>
  `,
  host: {
    class: 'sbb-icon-wrapper'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconSaLe {}

@NgModule({
  declarations: [SvgIconSaLe, IconSaLe],
  exports: [SvgIconSaLe, IconSaLe]
})
export class IconSaLeModule {}
