/* Autogenerated by @sbb-esta/angular-icons schematics */
// tslint:disable
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

@Component({
  selector: 'svg[sbbIconArrowRightMedium]',
  template: `
    <svg:path
      fill="none"
      stroke="#000"
      d="M7.5 18.737h18.735M20.25 24.75l5.985-6.012-5.985-5.988"
    />
  `,
  styles: [
    `
      :host-context(.sbb-icon-fixed-size) {
        width: 36px;
        height: 36px;
      }
      :host-context(.sbb-icon-inherit-color) [fill]:not([fill='none']) {
        fill: currentColor;
      }
      :host-context(.sbb-icon-inherit-color) [stroke]:not([stroke='none']) {
        stroke: currentColor;
      }
    `
  ],
  host: {
    xmlns: 'http://www.w3.org/2000/svg',
    viewBox: '0 0 36 36',
    class: 'sbb-icon sbb-icon-kom sbb-icon-arrow',
    focusable: 'false'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SvgIconArrowRightMedium {}

@Component({
  selector: 'sbb-icon-arrow-right-medium',
  template: `
    <svg sbbIconArrowRightMedium></svg>
  `,
  host: {
    class: 'sbb-icon-wrapper'
  },
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconArrowRightMedium {}

@NgModule({
  declarations: [SvgIconArrowRightMedium, IconArrowRightMedium],
  exports: [SvgIconArrowRightMedium, IconArrowRightMedium]
})
export class IconArrowRightMediumModule {}
