/*
 * Don't delete this file, it's autogenerated by the ACL icons build script
 */
import { ChangeDetectionStrategy, Component, NgModule } from '@angular/core';

import { IconBase } from '../../icon-base';

/** @deprecated Use `@sbb-esta/angular-icons` instead. */
@Component({
  selector: 'sbb-icon-service-vx',
  // tslint:disable-next-line
  template: `<svg [attr.class]="'sbb-svg-icon ' + svgClass" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 25 13"><path d="M0 0h2.6l1.2 10.1L9.3 0h2.8L4.8 13H1.7M21.1 0l-3.6 4.5L15.6 0h-2.8l2.8 5.9-6 7.1h3.2l4.1-5.2 2 5.2h2.8l-3-6.8L24.2 0"/></svg>`,
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IconServiceVxComponent extends IconBase {
  constructor() {
    super({ width: '25px', height: '13px', ratio: 1.9230769230769231 });
  }
}

/** @deprecated Use `@sbb-esta/angular-icons` instead. */
@NgModule({
  declarations: [IconServiceVxComponent],
  exports: [IconServiceVxComponent]
})
export class IconServiceVxModule {}
