/*
 * Autogenerated by schematics
 */
export * from './icon-document-check.module';
export * from './icon-document-image.module';
export * from './icon-document-lock.module';
export * from './icon-document-pdf.module';
export * from './icon-document-plus.module';
export * from './icon-document-ppt.module';
export * from './icon-document-sbb.module';
export * from './icon-document-sound.module';
export * from './icon-document-standard.module';
export * from './icon-document-text.module';
export * from './icon-document-video.module';
export * from './icon-document-zip.module';
export * from './icon-folder-info.module';
export * from './icon-folder-lock.module';
export * from './icon-folder-open.module';
export * from './icon-folder-open-arrow.module';
export * from './icon-folder-plus.module';
export * from './icon-metadata.module';
export * from './icon-two-folders.module';
export * from './icon-collection-document.module';
