name: Angular Components Sync
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 7 * * *'

jobs:
  update-issue:
    runs-on: ubuntu-latest
    steps:
    - name: Shallow checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: actions/setup-node@v1
      with:
        node-version: 16

    - name: "Yarn: Install global dependencies"
      run: yarn global add typescript ts-node

    - name: "Execute Angular Components Sync"
      run: ts-node scripts/angular-components-sync.ts
